// Code generated by ent, DO NOT EDIT.

package song

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldTitle, v))
}

// Artist applies equality check predicate on the "artist" field. It's identical to ArtistEQ.
func Artist(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldArtist, v))
}

// Lyrics applies equality check predicate on the "lyrics" field. It's identical to LyricsEQ.
func Lyrics(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldLyrics, v))
}

// LrcTimestamps applies equality check predicate on the "lrc_timestamps" field. It's identical to LrcTimestampsEQ.
func LrcTimestamps(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldLrcTimestamps, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldLanguage, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldTitle, v))
}

// ArtistEQ applies the EQ predicate on the "artist" field.
func ArtistEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldArtist, v))
}

// ArtistNEQ applies the NEQ predicate on the "artist" field.
func ArtistNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldArtist, v))
}

// ArtistIn applies the In predicate on the "artist" field.
func ArtistIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldArtist, vs...))
}

// ArtistNotIn applies the NotIn predicate on the "artist" field.
func ArtistNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldArtist, vs...))
}

// ArtistGT applies the GT predicate on the "artist" field.
func ArtistGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldArtist, v))
}

// ArtistGTE applies the GTE predicate on the "artist" field.
func ArtistGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldArtist, v))
}

// ArtistLT applies the LT predicate on the "artist" field.
func ArtistLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldArtist, v))
}

// ArtistLTE applies the LTE predicate on the "artist" field.
func ArtistLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldArtist, v))
}

// ArtistContains applies the Contains predicate on the "artist" field.
func ArtistContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldArtist, v))
}

// ArtistHasPrefix applies the HasPrefix predicate on the "artist" field.
func ArtistHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldArtist, v))
}

// ArtistHasSuffix applies the HasSuffix predicate on the "artist" field.
func ArtistHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldArtist, v))
}

// ArtistIsNil applies the IsNil predicate on the "artist" field.
func ArtistIsNil() predicate.Song {
	return predicate.Song(sql.FieldIsNull(FieldArtist))
}

// ArtistNotNil applies the NotNil predicate on the "artist" field.
func ArtistNotNil() predicate.Song {
	return predicate.Song(sql.FieldNotNull(FieldArtist))
}

// ArtistEqualFold applies the EqualFold predicate on the "artist" field.
func ArtistEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldArtist, v))
}

// ArtistContainsFold applies the ContainsFold predicate on the "artist" field.
func ArtistContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldArtist, v))
}

// LyricsEQ applies the EQ predicate on the "lyrics" field.
func LyricsEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldLyrics, v))
}

// LyricsNEQ applies the NEQ predicate on the "lyrics" field.
func LyricsNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldLyrics, v))
}

// LyricsIn applies the In predicate on the "lyrics" field.
func LyricsIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldLyrics, vs...))
}

// LyricsNotIn applies the NotIn predicate on the "lyrics" field.
func LyricsNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldLyrics, vs...))
}

// LyricsGT applies the GT predicate on the "lyrics" field.
func LyricsGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldLyrics, v))
}

// LyricsGTE applies the GTE predicate on the "lyrics" field.
func LyricsGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldLyrics, v))
}

// LyricsLT applies the LT predicate on the "lyrics" field.
func LyricsLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldLyrics, v))
}

// LyricsLTE applies the LTE predicate on the "lyrics" field.
func LyricsLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldLyrics, v))
}

// LyricsContains applies the Contains predicate on the "lyrics" field.
func LyricsContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldLyrics, v))
}

// LyricsHasPrefix applies the HasPrefix predicate on the "lyrics" field.
func LyricsHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldLyrics, v))
}

// LyricsHasSuffix applies the HasSuffix predicate on the "lyrics" field.
func LyricsHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldLyrics, v))
}

// LyricsEqualFold applies the EqualFold predicate on the "lyrics" field.
func LyricsEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldLyrics, v))
}

// LyricsContainsFold applies the ContainsFold predicate on the "lyrics" field.
func LyricsContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldLyrics, v))
}

// LrcTimestampsEQ applies the EQ predicate on the "lrc_timestamps" field.
func LrcTimestampsEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldLrcTimestamps, v))
}

// LrcTimestampsNEQ applies the NEQ predicate on the "lrc_timestamps" field.
func LrcTimestampsNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldLrcTimestamps, v))
}

// LrcTimestampsIn applies the In predicate on the "lrc_timestamps" field.
func LrcTimestampsIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldLrcTimestamps, vs...))
}

// LrcTimestampsNotIn applies the NotIn predicate on the "lrc_timestamps" field.
func LrcTimestampsNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldLrcTimestamps, vs...))
}

// LrcTimestampsGT applies the GT predicate on the "lrc_timestamps" field.
func LrcTimestampsGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldLrcTimestamps, v))
}

// LrcTimestampsGTE applies the GTE predicate on the "lrc_timestamps" field.
func LrcTimestampsGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldLrcTimestamps, v))
}

// LrcTimestampsLT applies the LT predicate on the "lrc_timestamps" field.
func LrcTimestampsLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldLrcTimestamps, v))
}

// LrcTimestampsLTE applies the LTE predicate on the "lrc_timestamps" field.
func LrcTimestampsLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldLrcTimestamps, v))
}

// LrcTimestampsContains applies the Contains predicate on the "lrc_timestamps" field.
func LrcTimestampsContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldLrcTimestamps, v))
}

// LrcTimestampsHasPrefix applies the HasPrefix predicate on the "lrc_timestamps" field.
func LrcTimestampsHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldLrcTimestamps, v))
}

// LrcTimestampsHasSuffix applies the HasSuffix predicate on the "lrc_timestamps" field.
func LrcTimestampsHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldLrcTimestamps, v))
}

// LrcTimestampsIsNil applies the IsNil predicate on the "lrc_timestamps" field.
func LrcTimestampsIsNil() predicate.Song {
	return predicate.Song(sql.FieldIsNull(FieldLrcTimestamps))
}

// LrcTimestampsNotNil applies the NotNil predicate on the "lrc_timestamps" field.
func LrcTimestampsNotNil() predicate.Song {
	return predicate.Song(sql.FieldNotNull(FieldLrcTimestamps))
}

// LrcTimestampsEqualFold applies the EqualFold predicate on the "lrc_timestamps" field.
func LrcTimestampsEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldLrcTimestamps, v))
}

// LrcTimestampsContainsFold applies the ContainsFold predicate on the "lrc_timestamps" field.
func LrcTimestampsContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldLrcTimestamps, v))
}

// LrcContentIsNil applies the IsNil predicate on the "lrc_content" field.
func LrcContentIsNil() predicate.Song {
	return predicate.Song(sql.FieldIsNull(FieldLrcContent))
}

// LrcContentNotNil applies the NotNil predicate on the "lrc_content" field.
func LrcContentNotNil() predicate.Song {
	return predicate.Song(sql.FieldNotNull(FieldLrcContent))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Song {
	return predicate.Song(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Song {
	return predicate.Song(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageIsNil applies the IsNil predicate on the "language" field.
func LanguageIsNil() predicate.Song {
	return predicate.Song(sql.FieldIsNull(FieldLanguage))
}

// LanguageNotNil applies the NotNil predicate on the "language" field.
func LanguageNotNil() predicate.Song {
	return predicate.Song(sql.FieldNotNull(FieldLanguage))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Song {
	return predicate.Song(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Song {
	return predicate.Song(sql.FieldContainsFold(FieldLanguage, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldUserID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Song {
	return predicate.Song(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Song {
	return predicate.Song(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Song {
	return predicate.Song(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Song {
	return predicate.Song(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Song {
	return predicate.Song(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlaylistSongs applies the HasEdge predicate on the "playlist_songs" edge.
func HasPlaylistSongs() predicate.Song {
	return predicate.Song(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlaylistSongsTable, PlaylistSongsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlaylistSongsWith applies the HasEdge predicate on the "playlist_songs" edge with a given conditions (other predicates).
func HasPlaylistSongsWith(preds ...predicate.PlaylistSong) predicate.Song {
	return predicate.Song(func(s *sql.Selector) {
		step := newPlaylistSongsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Song) predicate.Song {
	return predicate.Song(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Song) predicate.Song {
	return predicate.Song(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Song) predicate.Song {
	return predicate.Song(sql.NotPredicates(p))
}
