// Code generated by ent, DO NOT EDIT.

package settings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the settings type in the database.
	Label = "settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDisplayLines holds the string denoting the display_lines field in the database.
	FieldDisplayLines = "display_lines"
	// FieldFontSize holds the string denoting the font_size field in the database.
	FieldFontSize = "font_size"
	// FieldFontFamily holds the string denoting the font_family field in the database.
	FieldFontFamily = "font_family"
	// FieldTheme holds the string denoting the theme field in the database.
	FieldTheme = "theme"
	// FieldShowBackground holds the string denoting the show_background field in the database.
	FieldShowBackground = "show_background"
	// FieldBackgroundColor holds the string denoting the background_color field in the database.
	FieldBackgroundColor = "background_color"
	// FieldTextColor holds the string denoting the text_color field in the database.
	FieldTextColor = "text_color"
	// FieldHighlightColor holds the string denoting the highlight_color field in the database.
	FieldHighlightColor = "highlight_color"
	// FieldAutoScroll holds the string denoting the auto_scroll field in the database.
	FieldAutoScroll = "auto_scroll"
	// FieldScrollDuration holds the string denoting the scroll_duration field in the database.
	FieldScrollDuration = "scroll_duration"
	// FieldEnableAnimation holds the string denoting the enable_animation field in the database.
	FieldEnableAnimation = "enable_animation"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the settings in the database.
	Table = "settings"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "settings"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for settings fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDisplayLines,
	FieldFontSize,
	FieldFontFamily,
	FieldTheme,
	FieldShowBackground,
	FieldBackgroundColor,
	FieldTextColor,
	FieldHighlightColor,
	FieldAutoScroll,
	FieldScrollDuration,
	FieldEnableAnimation,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDisplayLines holds the default value on creation for the "display_lines" field.
	DefaultDisplayLines int
	// DefaultFontSize holds the default value on creation for the "font_size" field.
	DefaultFontSize int
	// DefaultFontFamily holds the default value on creation for the "font_family" field.
	DefaultFontFamily string
	// FontFamilyValidator is a validator for the "font_family" field. It is called by the builders before save.
	FontFamilyValidator func(string) error
	// DefaultTheme holds the default value on creation for the "theme" field.
	DefaultTheme string
	// ThemeValidator is a validator for the "theme" field. It is called by the builders before save.
	ThemeValidator func(string) error
	// DefaultShowBackground holds the default value on creation for the "show_background" field.
	DefaultShowBackground bool
	// BackgroundColorValidator is a validator for the "background_color" field. It is called by the builders before save.
	BackgroundColorValidator func(string) error
	// TextColorValidator is a validator for the "text_color" field. It is called by the builders before save.
	TextColorValidator func(string) error
	// HighlightColorValidator is a validator for the "highlight_color" field. It is called by the builders before save.
	HighlightColorValidator func(string) error
	// DefaultAutoScroll holds the default value on creation for the "auto_scroll" field.
	DefaultAutoScroll bool
	// DefaultScrollDuration holds the default value on creation for the "scroll_duration" field.
	DefaultScrollDuration int
	// DefaultEnableAnimation holds the default value on creation for the "enable_animation" field.
	DefaultEnableAnimation bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Settings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDisplayLines orders the results by the display_lines field.
func ByDisplayLines(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayLines, opts...).ToFunc()
}

// ByFontSize orders the results by the font_size field.
func ByFontSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFontSize, opts...).ToFunc()
}

// ByFontFamily orders the results by the font_family field.
func ByFontFamily(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFontFamily, opts...).ToFunc()
}

// ByTheme orders the results by the theme field.
func ByTheme(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTheme, opts...).ToFunc()
}

// ByShowBackground orders the results by the show_background field.
func ByShowBackground(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShowBackground, opts...).ToFunc()
}

// ByBackgroundColor orders the results by the background_color field.
func ByBackgroundColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackgroundColor, opts...).ToFunc()
}

// ByTextColor orders the results by the text_color field.
func ByTextColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTextColor, opts...).ToFunc()
}

// ByHighlightColor orders the results by the highlight_color field.
func ByHighlightColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHighlightColor, opts...).ToFunc()
}

// ByAutoScroll orders the results by the auto_scroll field.
func ByAutoScroll(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoScroll, opts...).ToFunc()
}

// ByScrollDuration orders the results by the scroll_duration field.
func ByScrollDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScrollDuration, opts...).ToFunc()
}

// ByEnableAnimation orders the results by the enable_animation field.
func ByEnableAnimation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnableAnimation, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
