// Code generated by ent, DO NOT EDIT.

package settings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUserID, v))
}

// DisplayLines applies equality check predicate on the "display_lines" field. It's identical to DisplayLinesEQ.
func DisplayLines(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldDisplayLines, v))
}

// FontSize applies equality check predicate on the "font_size" field. It's identical to FontSizeEQ.
func FontSize(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldFontSize, v))
}

// FontFamily applies equality check predicate on the "font_family" field. It's identical to FontFamilyEQ.
func FontFamily(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldFontFamily, v))
}

// Theme applies equality check predicate on the "theme" field. It's identical to ThemeEQ.
func Theme(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldTheme, v))
}

// ShowBackground applies equality check predicate on the "show_background" field. It's identical to ShowBackgroundEQ.
func ShowBackground(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldShowBackground, v))
}

// BackgroundColor applies equality check predicate on the "background_color" field. It's identical to BackgroundColorEQ.
func BackgroundColor(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldBackgroundColor, v))
}

// TextColor applies equality check predicate on the "text_color" field. It's identical to TextColorEQ.
func TextColor(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldTextColor, v))
}

// HighlightColor applies equality check predicate on the "highlight_color" field. It's identical to HighlightColorEQ.
func HighlightColor(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldHighlightColor, v))
}

// AutoScroll applies equality check predicate on the "auto_scroll" field. It's identical to AutoScrollEQ.
func AutoScroll(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldAutoScroll, v))
}

// ScrollDuration applies equality check predicate on the "scroll_duration" field. It's identical to ScrollDurationEQ.
func ScrollDuration(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldScrollDuration, v))
}

// EnableAnimation applies equality check predicate on the "enable_animation" field. It's identical to EnableAnimationEQ.
func EnableAnimation(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldEnableAnimation, v))
}

// LineSpacing applies equality check predicate on the "line_spacing" field. It's identical to LineSpacingEQ.
func LineSpacing(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldLineSpacing, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldUserID, vs...))
}

// DisplayLinesEQ applies the EQ predicate on the "display_lines" field.
func DisplayLinesEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldDisplayLines, v))
}

// DisplayLinesNEQ applies the NEQ predicate on the "display_lines" field.
func DisplayLinesNEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldDisplayLines, v))
}

// DisplayLinesIn applies the In predicate on the "display_lines" field.
func DisplayLinesIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldDisplayLines, vs...))
}

// DisplayLinesNotIn applies the NotIn predicate on the "display_lines" field.
func DisplayLinesNotIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldDisplayLines, vs...))
}

// DisplayLinesGT applies the GT predicate on the "display_lines" field.
func DisplayLinesGT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldDisplayLines, v))
}

// DisplayLinesGTE applies the GTE predicate on the "display_lines" field.
func DisplayLinesGTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldDisplayLines, v))
}

// DisplayLinesLT applies the LT predicate on the "display_lines" field.
func DisplayLinesLT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldDisplayLines, v))
}

// DisplayLinesLTE applies the LTE predicate on the "display_lines" field.
func DisplayLinesLTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldDisplayLines, v))
}

// FontSizeEQ applies the EQ predicate on the "font_size" field.
func FontSizeEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldFontSize, v))
}

// FontSizeNEQ applies the NEQ predicate on the "font_size" field.
func FontSizeNEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldFontSize, v))
}

// FontSizeIn applies the In predicate on the "font_size" field.
func FontSizeIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldFontSize, vs...))
}

// FontSizeNotIn applies the NotIn predicate on the "font_size" field.
func FontSizeNotIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldFontSize, vs...))
}

// FontSizeGT applies the GT predicate on the "font_size" field.
func FontSizeGT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldFontSize, v))
}

// FontSizeGTE applies the GTE predicate on the "font_size" field.
func FontSizeGTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldFontSize, v))
}

// FontSizeLT applies the LT predicate on the "font_size" field.
func FontSizeLT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldFontSize, v))
}

// FontSizeLTE applies the LTE predicate on the "font_size" field.
func FontSizeLTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldFontSize, v))
}

// FontFamilyEQ applies the EQ predicate on the "font_family" field.
func FontFamilyEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldFontFamily, v))
}

// FontFamilyNEQ applies the NEQ predicate on the "font_family" field.
func FontFamilyNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldFontFamily, v))
}

// FontFamilyIn applies the In predicate on the "font_family" field.
func FontFamilyIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldFontFamily, vs...))
}

// FontFamilyNotIn applies the NotIn predicate on the "font_family" field.
func FontFamilyNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldFontFamily, vs...))
}

// FontFamilyGT applies the GT predicate on the "font_family" field.
func FontFamilyGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldFontFamily, v))
}

// FontFamilyGTE applies the GTE predicate on the "font_family" field.
func FontFamilyGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldFontFamily, v))
}

// FontFamilyLT applies the LT predicate on the "font_family" field.
func FontFamilyLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldFontFamily, v))
}

// FontFamilyLTE applies the LTE predicate on the "font_family" field.
func FontFamilyLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldFontFamily, v))
}

// FontFamilyContains applies the Contains predicate on the "font_family" field.
func FontFamilyContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldFontFamily, v))
}

// FontFamilyHasPrefix applies the HasPrefix predicate on the "font_family" field.
func FontFamilyHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldFontFamily, v))
}

// FontFamilyHasSuffix applies the HasSuffix predicate on the "font_family" field.
func FontFamilyHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldFontFamily, v))
}

// FontFamilyEqualFold applies the EqualFold predicate on the "font_family" field.
func FontFamilyEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldFontFamily, v))
}

// FontFamilyContainsFold applies the ContainsFold predicate on the "font_family" field.
func FontFamilyContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldFontFamily, v))
}

// ThemeEQ applies the EQ predicate on the "theme" field.
func ThemeEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldTheme, v))
}

// ThemeNEQ applies the NEQ predicate on the "theme" field.
func ThemeNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldTheme, v))
}

// ThemeIn applies the In predicate on the "theme" field.
func ThemeIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldTheme, vs...))
}

// ThemeNotIn applies the NotIn predicate on the "theme" field.
func ThemeNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldTheme, vs...))
}

// ThemeGT applies the GT predicate on the "theme" field.
func ThemeGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldTheme, v))
}

// ThemeGTE applies the GTE predicate on the "theme" field.
func ThemeGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldTheme, v))
}

// ThemeLT applies the LT predicate on the "theme" field.
func ThemeLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldTheme, v))
}

// ThemeLTE applies the LTE predicate on the "theme" field.
func ThemeLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldTheme, v))
}

// ThemeContains applies the Contains predicate on the "theme" field.
func ThemeContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldTheme, v))
}

// ThemeHasPrefix applies the HasPrefix predicate on the "theme" field.
func ThemeHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldTheme, v))
}

// ThemeHasSuffix applies the HasSuffix predicate on the "theme" field.
func ThemeHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldTheme, v))
}

// ThemeEqualFold applies the EqualFold predicate on the "theme" field.
func ThemeEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldTheme, v))
}

// ThemeContainsFold applies the ContainsFold predicate on the "theme" field.
func ThemeContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldTheme, v))
}

// ShowBackgroundEQ applies the EQ predicate on the "show_background" field.
func ShowBackgroundEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldShowBackground, v))
}

// ShowBackgroundNEQ applies the NEQ predicate on the "show_background" field.
func ShowBackgroundNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldShowBackground, v))
}

// BackgroundColorEQ applies the EQ predicate on the "background_color" field.
func BackgroundColorEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldBackgroundColor, v))
}

// BackgroundColorNEQ applies the NEQ predicate on the "background_color" field.
func BackgroundColorNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldBackgroundColor, v))
}

// BackgroundColorIn applies the In predicate on the "background_color" field.
func BackgroundColorIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldBackgroundColor, vs...))
}

// BackgroundColorNotIn applies the NotIn predicate on the "background_color" field.
func BackgroundColorNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldBackgroundColor, vs...))
}

// BackgroundColorGT applies the GT predicate on the "background_color" field.
func BackgroundColorGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldBackgroundColor, v))
}

// BackgroundColorGTE applies the GTE predicate on the "background_color" field.
func BackgroundColorGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldBackgroundColor, v))
}

// BackgroundColorLT applies the LT predicate on the "background_color" field.
func BackgroundColorLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldBackgroundColor, v))
}

// BackgroundColorLTE applies the LTE predicate on the "background_color" field.
func BackgroundColorLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldBackgroundColor, v))
}

// BackgroundColorContains applies the Contains predicate on the "background_color" field.
func BackgroundColorContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldBackgroundColor, v))
}

// BackgroundColorHasPrefix applies the HasPrefix predicate on the "background_color" field.
func BackgroundColorHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldBackgroundColor, v))
}

// BackgroundColorHasSuffix applies the HasSuffix predicate on the "background_color" field.
func BackgroundColorHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldBackgroundColor, v))
}

// BackgroundColorIsNil applies the IsNil predicate on the "background_color" field.
func BackgroundColorIsNil() predicate.Settings {
	return predicate.Settings(sql.FieldIsNull(FieldBackgroundColor))
}

// BackgroundColorNotNil applies the NotNil predicate on the "background_color" field.
func BackgroundColorNotNil() predicate.Settings {
	return predicate.Settings(sql.FieldNotNull(FieldBackgroundColor))
}

// BackgroundColorEqualFold applies the EqualFold predicate on the "background_color" field.
func BackgroundColorEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldBackgroundColor, v))
}

// BackgroundColorContainsFold applies the ContainsFold predicate on the "background_color" field.
func BackgroundColorContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldBackgroundColor, v))
}

// TextColorEQ applies the EQ predicate on the "text_color" field.
func TextColorEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldTextColor, v))
}

// TextColorNEQ applies the NEQ predicate on the "text_color" field.
func TextColorNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldTextColor, v))
}

// TextColorIn applies the In predicate on the "text_color" field.
func TextColorIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldTextColor, vs...))
}

// TextColorNotIn applies the NotIn predicate on the "text_color" field.
func TextColorNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldTextColor, vs...))
}

// TextColorGT applies the GT predicate on the "text_color" field.
func TextColorGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldTextColor, v))
}

// TextColorGTE applies the GTE predicate on the "text_color" field.
func TextColorGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldTextColor, v))
}

// TextColorLT applies the LT predicate on the "text_color" field.
func TextColorLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldTextColor, v))
}

// TextColorLTE applies the LTE predicate on the "text_color" field.
func TextColorLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldTextColor, v))
}

// TextColorContains applies the Contains predicate on the "text_color" field.
func TextColorContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldTextColor, v))
}

// TextColorHasPrefix applies the HasPrefix predicate on the "text_color" field.
func TextColorHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldTextColor, v))
}

// TextColorHasSuffix applies the HasSuffix predicate on the "text_color" field.
func TextColorHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldTextColor, v))
}

// TextColorIsNil applies the IsNil predicate on the "text_color" field.
func TextColorIsNil() predicate.Settings {
	return predicate.Settings(sql.FieldIsNull(FieldTextColor))
}

// TextColorNotNil applies the NotNil predicate on the "text_color" field.
func TextColorNotNil() predicate.Settings {
	return predicate.Settings(sql.FieldNotNull(FieldTextColor))
}

// TextColorEqualFold applies the EqualFold predicate on the "text_color" field.
func TextColorEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldTextColor, v))
}

// TextColorContainsFold applies the ContainsFold predicate on the "text_color" field.
func TextColorContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldTextColor, v))
}

// HighlightColorEQ applies the EQ predicate on the "highlight_color" field.
func HighlightColorEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldHighlightColor, v))
}

// HighlightColorNEQ applies the NEQ predicate on the "highlight_color" field.
func HighlightColorNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldHighlightColor, v))
}

// HighlightColorIn applies the In predicate on the "highlight_color" field.
func HighlightColorIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldHighlightColor, vs...))
}

// HighlightColorNotIn applies the NotIn predicate on the "highlight_color" field.
func HighlightColorNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldHighlightColor, vs...))
}

// HighlightColorGT applies the GT predicate on the "highlight_color" field.
func HighlightColorGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldHighlightColor, v))
}

// HighlightColorGTE applies the GTE predicate on the "highlight_color" field.
func HighlightColorGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldHighlightColor, v))
}

// HighlightColorLT applies the LT predicate on the "highlight_color" field.
func HighlightColorLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldHighlightColor, v))
}

// HighlightColorLTE applies the LTE predicate on the "highlight_color" field.
func HighlightColorLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldHighlightColor, v))
}

// HighlightColorContains applies the Contains predicate on the "highlight_color" field.
func HighlightColorContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldHighlightColor, v))
}

// HighlightColorHasPrefix applies the HasPrefix predicate on the "highlight_color" field.
func HighlightColorHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldHighlightColor, v))
}

// HighlightColorHasSuffix applies the HasSuffix predicate on the "highlight_color" field.
func HighlightColorHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldHighlightColor, v))
}

// HighlightColorIsNil applies the IsNil predicate on the "highlight_color" field.
func HighlightColorIsNil() predicate.Settings {
	return predicate.Settings(sql.FieldIsNull(FieldHighlightColor))
}

// HighlightColorNotNil applies the NotNil predicate on the "highlight_color" field.
func HighlightColorNotNil() predicate.Settings {
	return predicate.Settings(sql.FieldNotNull(FieldHighlightColor))
}

// HighlightColorEqualFold applies the EqualFold predicate on the "highlight_color" field.
func HighlightColorEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldHighlightColor, v))
}

// HighlightColorContainsFold applies the ContainsFold predicate on the "highlight_color" field.
func HighlightColorContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldHighlightColor, v))
}

// AutoScrollEQ applies the EQ predicate on the "auto_scroll" field.
func AutoScrollEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldAutoScroll, v))
}

// AutoScrollNEQ applies the NEQ predicate on the "auto_scroll" field.
func AutoScrollNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldAutoScroll, v))
}

// ScrollDurationEQ applies the EQ predicate on the "scroll_duration" field.
func ScrollDurationEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldScrollDuration, v))
}

// ScrollDurationNEQ applies the NEQ predicate on the "scroll_duration" field.
func ScrollDurationNEQ(v int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldScrollDuration, v))
}

// ScrollDurationIn applies the In predicate on the "scroll_duration" field.
func ScrollDurationIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldScrollDuration, vs...))
}

// ScrollDurationNotIn applies the NotIn predicate on the "scroll_duration" field.
func ScrollDurationNotIn(vs ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldScrollDuration, vs...))
}

// ScrollDurationGT applies the GT predicate on the "scroll_duration" field.
func ScrollDurationGT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldScrollDuration, v))
}

// ScrollDurationGTE applies the GTE predicate on the "scroll_duration" field.
func ScrollDurationGTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldScrollDuration, v))
}

// ScrollDurationLT applies the LT predicate on the "scroll_duration" field.
func ScrollDurationLT(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldScrollDuration, v))
}

// ScrollDurationLTE applies the LTE predicate on the "scroll_duration" field.
func ScrollDurationLTE(v int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldScrollDuration, v))
}

// EnableAnimationEQ applies the EQ predicate on the "enable_animation" field.
func EnableAnimationEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldEnableAnimation, v))
}

// EnableAnimationNEQ applies the NEQ predicate on the "enable_animation" field.
func EnableAnimationNEQ(v bool) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldEnableAnimation, v))
}

// LineSpacingEQ applies the EQ predicate on the "line_spacing" field.
func LineSpacingEQ(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldLineSpacing, v))
}

// LineSpacingNEQ applies the NEQ predicate on the "line_spacing" field.
func LineSpacingNEQ(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldLineSpacing, v))
}

// LineSpacingIn applies the In predicate on the "line_spacing" field.
func LineSpacingIn(vs ...float64) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldLineSpacing, vs...))
}

// LineSpacingNotIn applies the NotIn predicate on the "line_spacing" field.
func LineSpacingNotIn(vs ...float64) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldLineSpacing, vs...))
}

// LineSpacingGT applies the GT predicate on the "line_spacing" field.
func LineSpacingGT(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldLineSpacing, v))
}

// LineSpacingGTE applies the GTE predicate on the "line_spacing" field.
func LineSpacingGTE(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldLineSpacing, v))
}

// LineSpacingLT applies the LT predicate on the "line_spacing" field.
func LineSpacingLT(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldLineSpacing, v))
}

// LineSpacingLTE applies the LTE predicate on the "line_spacing" field.
func LineSpacingLTE(v float64) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldLineSpacing, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Settings {
	return predicate.Settings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Settings {
	return predicate.Settings(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.NotPredicates(p))
}
