// Code generated by ent, DO NOT EDIT.

package playlistsong

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the playlistsong type in the database.
	Label = "playlist_song"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlaylistID holds the string denoting the playlist_id field in the database.
	FieldPlaylistID = "playlist_id"
	// FieldSongID holds the string denoting the song_id field in the database.
	FieldSongID = "song_id"
	// FieldOrderIndex holds the string denoting the order_index field in the database.
	FieldOrderIndex = "order_index"
	// FieldAddedAt holds the string denoting the added_at field in the database.
	FieldAddedAt = "added_at"
	// EdgePlaylist holds the string denoting the playlist edge name in mutations.
	EdgePlaylist = "playlist"
	// EdgeSong holds the string denoting the song edge name in mutations.
	EdgeSong = "song"
	// Table holds the table name of the playlistsong in the database.
	Table = "playlist_songs"
	// PlaylistTable is the table that holds the playlist relation/edge.
	PlaylistTable = "playlist_songs"
	// PlaylistInverseTable is the table name for the Playlist entity.
	// It exists in this package in order to avoid circular dependency with the "playlist" package.
	PlaylistInverseTable = "playlists"
	// PlaylistColumn is the table column denoting the playlist relation/edge.
	PlaylistColumn = "playlist_id"
	// SongTable is the table that holds the song relation/edge.
	SongTable = "playlist_songs"
	// SongInverseTable is the table name for the Song entity.
	// It exists in this package in order to avoid circular dependency with the "song" package.
	SongInverseTable = "songs"
	// SongColumn is the table column denoting the song relation/edge.
	SongColumn = "song_id"
)

// Columns holds all SQL columns for playlistsong fields.
var Columns = []string{
	FieldID,
	FieldPlaylistID,
	FieldSongID,
	FieldOrderIndex,
	FieldAddedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAddedAt holds the default value on creation for the "added_at" field.
	DefaultAddedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PlaylistSong queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlaylistID orders the results by the playlist_id field.
func ByPlaylistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaylistID, opts...).ToFunc()
}

// BySongID orders the results by the song_id field.
func BySongID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSongID, opts...).ToFunc()
}

// ByOrderIndex orders the results by the order_index field.
func ByOrderIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderIndex, opts...).ToFunc()
}

// ByAddedAt orders the results by the added_at field.
func ByAddedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddedAt, opts...).ToFunc()
}

// ByPlaylistField orders the results by playlist field.
func ByPlaylistField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlaylistStep(), sql.OrderByField(field, opts...))
	}
}

// BySongField orders the results by song field.
func BySongField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSongStep(), sql.OrderByField(field, opts...))
	}
}
func newPlaylistStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlaylistInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlaylistTable, PlaylistColumn),
	)
}
func newSongStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SongInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SongTable, SongColumn),
	)
}
