// Code generated by ent, DO NOT EDIT.

package playlistsong

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldID, id))
}

// PlaylistID applies equality check predicate on the "playlist_id" field. It's identical to PlaylistIDEQ.
func PlaylistID(v uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldPlaylistID, v))
}

// SongID applies equality check predicate on the "song_id" field. It's identical to SongIDEQ.
func SongID(v uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldSongID, v))
}

// OrderIndex applies equality check predicate on the "order_index" field. It's identical to OrderIndexEQ.
func OrderIndex(v int) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldOrderIndex, v))
}

// AddedAt applies equality check predicate on the "added_at" field. It's identical to AddedAtEQ.
func AddedAt(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldAddedAt, v))
}

// PlaylistIDEQ applies the EQ predicate on the "playlist_id" field.
func PlaylistIDEQ(v uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldPlaylistID, v))
}

// PlaylistIDNEQ applies the NEQ predicate on the "playlist_id" field.
func PlaylistIDNEQ(v uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldPlaylistID, v))
}

// PlaylistIDIn applies the In predicate on the "playlist_id" field.
func PlaylistIDIn(vs ...uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldPlaylistID, vs...))
}

// PlaylistIDNotIn applies the NotIn predicate on the "playlist_id" field.
func PlaylistIDNotIn(vs ...uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldPlaylistID, vs...))
}

// SongIDEQ applies the EQ predicate on the "song_id" field.
func SongIDEQ(v uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldSongID, v))
}

// SongIDNEQ applies the NEQ predicate on the "song_id" field.
func SongIDNEQ(v uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldSongID, v))
}

// SongIDIn applies the In predicate on the "song_id" field.
func SongIDIn(vs ...uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldSongID, vs...))
}

// SongIDNotIn applies the NotIn predicate on the "song_id" field.
func SongIDNotIn(vs ...uuid.UUID) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldSongID, vs...))
}

// OrderIndexEQ applies the EQ predicate on the "order_index" field.
func OrderIndexEQ(v int) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldOrderIndex, v))
}

// OrderIndexNEQ applies the NEQ predicate on the "order_index" field.
func OrderIndexNEQ(v int) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldOrderIndex, v))
}

// OrderIndexIn applies the In predicate on the "order_index" field.
func OrderIndexIn(vs ...int) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldOrderIndex, vs...))
}

// OrderIndexNotIn applies the NotIn predicate on the "order_index" field.
func OrderIndexNotIn(vs ...int) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldOrderIndex, vs...))
}

// OrderIndexGT applies the GT predicate on the "order_index" field.
func OrderIndexGT(v int) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldOrderIndex, v))
}

// OrderIndexGTE applies the GTE predicate on the "order_index" field.
func OrderIndexGTE(v int) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldOrderIndex, v))
}

// OrderIndexLT applies the LT predicate on the "order_index" field.
func OrderIndexLT(v int) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldOrderIndex, v))
}

// OrderIndexLTE applies the LTE predicate on the "order_index" field.
func OrderIndexLTE(v int) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldOrderIndex, v))
}

// AddedAtEQ applies the EQ predicate on the "added_at" field.
func AddedAtEQ(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldEQ(FieldAddedAt, v))
}

// AddedAtNEQ applies the NEQ predicate on the "added_at" field.
func AddedAtNEQ(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNEQ(FieldAddedAt, v))
}

// AddedAtIn applies the In predicate on the "added_at" field.
func AddedAtIn(vs ...time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldIn(FieldAddedAt, vs...))
}

// AddedAtNotIn applies the NotIn predicate on the "added_at" field.
func AddedAtNotIn(vs ...time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldNotIn(FieldAddedAt, vs...))
}

// AddedAtGT applies the GT predicate on the "added_at" field.
func AddedAtGT(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGT(FieldAddedAt, v))
}

// AddedAtGTE applies the GTE predicate on the "added_at" field.
func AddedAtGTE(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldGTE(FieldAddedAt, v))
}

// AddedAtLT applies the LT predicate on the "added_at" field.
func AddedAtLT(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLT(FieldAddedAt, v))
}

// AddedAtLTE applies the LTE predicate on the "added_at" field.
func AddedAtLTE(v time.Time) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.FieldLTE(FieldAddedAt, v))
}

// HasPlaylist applies the HasEdge predicate on the "playlist" edge.
func HasPlaylist() predicate.PlaylistSong {
	return predicate.PlaylistSong(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlaylistTable, PlaylistColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlaylistWith applies the HasEdge predicate on the "playlist" edge with a given conditions (other predicates).
func HasPlaylistWith(preds ...predicate.Playlist) predicate.PlaylistSong {
	return predicate.PlaylistSong(func(s *sql.Selector) {
		step := newPlaylistStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSong applies the HasEdge predicate on the "song" edge.
func HasSong() predicate.PlaylistSong {
	return predicate.PlaylistSong(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SongTable, SongColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSongWith applies the HasEdge predicate on the "song" edge with a given conditions (other predicates).
func HasSongWith(preds ...predicate.Song) predicate.PlaylistSong {
	return predicate.PlaylistSong(func(s *sql.Selector) {
		step := newSongStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlaylistSong) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlaylistSong) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlaylistSong) predicate.PlaylistSong {
	return predicate.PlaylistSong(sql.NotPredicates(p))
}
