// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PlaylistsColumns holds the columns for the "playlists" table.
	PlaylistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// PlaylistsTable holds the schema information for the "playlists" table.
	PlaylistsTable = &schema.Table{
		Name:       "playlists",
		Columns:    PlaylistsColumns,
		PrimaryKey: []*schema.Column{PlaylistsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "playlists_users_playlists",
				Columns:    []*schema.Column{PlaylistsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PlaylistSongsColumns holds the columns for the "playlist_songs" table.
	PlaylistSongsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "order_index", Type: field.TypeInt},
		{Name: "added_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "playlist_id", Type: field.TypeUUID},
		{Name: "song_id", Type: field.TypeUUID},
	}
	// PlaylistSongsTable holds the schema information for the "playlist_songs" table.
	PlaylistSongsTable = &schema.Table{
		Name:       "playlist_songs",
		Columns:    PlaylistSongsColumns,
		PrimaryKey: []*schema.Column{PlaylistSongsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "playlist_songs_playlists_playlist_songs",
				Columns:    []*schema.Column{PlaylistSongsColumns[3]},
				RefColumns: []*schema.Column{PlaylistsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "playlist_songs_songs_playlist_songs",
				Columns:    []*schema.Column{PlaylistSongsColumns[4]},
				RefColumns: []*schema.Column{SongsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "playlistsong_playlist_id_song_id_order_index",
				Unique:  true,
				Columns: []*schema.Column{PlaylistSongsColumns[3], PlaylistSongsColumns[4], PlaylistSongsColumns[1]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "token", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "display_lines", Type: field.TypeInt, Default: 4},
		{Name: "font_size", Type: field.TypeInt, Default: 24},
		{Name: "font_family", Type: field.TypeString, Size: 100, Default: "Inter"},
		{Name: "theme", Type: field.TypeString, Size: 50, Default: "dark"},
		{Name: "show_background", Type: field.TypeBool, Default: true},
		{Name: "background_color", Type: field.TypeString, Nullable: true, Size: 7},
		{Name: "text_color", Type: field.TypeString, Nullable: true, Size: 7},
		{Name: "highlight_color", Type: field.TypeString, Nullable: true, Size: 7},
		{Name: "auto_scroll", Type: field.TypeBool, Default: true},
		{Name: "scroll_duration", Type: field.TypeInt, Default: 300},
		{Name: "enable_animation", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeUUID, Unique: true},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "settings_users_settings",
				Columns:    []*schema.Column{SettingsColumns[14]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SongsColumns holds the columns for the "songs" table.
	SongsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "artist", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "lyrics", Type: field.TypeString, Size: 2147483647},
		{Name: "lrc_timestamps", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "lrc_content", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "language", Type: field.TypeString, Nullable: true, Size: 2},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// SongsTable holds the schema information for the "songs" table.
	SongsTable = &schema.Table{
		Name:       "songs",
		Columns:    SongsColumns,
		PrimaryKey: []*schema.Column{SongsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "songs_users_songs",
				Columns:    []*schema.Column{SongsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "password_hash", Type: field.TypeString, Size: 255},
		{Name: "name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PlaylistsTable,
		PlaylistSongsTable,
		SessionsTable,
		SettingsTable,
		SongsTable,
		UsersTable,
	}
)

func init() {
	PlaylistsTable.ForeignKeys[0].RefTable = UsersTable
	PlaylistsTable.Annotation = &entsql.Annotation{
		Table: "playlists",
	}
	PlaylistSongsTable.ForeignKeys[0].RefTable = PlaylistsTable
	PlaylistSongsTable.ForeignKeys[1].RefTable = SongsTable
	PlaylistSongsTable.Annotation = &entsql.Annotation{
		Table: "playlist_songs",
	}
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	SessionsTable.Annotation = &entsql.Annotation{
		Table: "sessions",
	}
	SettingsTable.ForeignKeys[0].RefTable = UsersTable
	SettingsTable.Annotation = &entsql.Annotation{
		Table: "settings",
	}
	SongsTable.ForeignKeys[0].RefTable = UsersTable
	SongsTable.Annotation = &entsql.Annotation{
		Table: "songs",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
