// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/playlist"
	"github.com/raymondchen/ly-backend/internal/ent/playlistsong"
	"github.com/raymondchen/ly-backend/internal/ent/song"
)

// PlaylistSong is the model entity for the PlaylistSong schema.
type PlaylistSong struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PlaylistID holds the value of the "playlist_id" field.
	PlaylistID uuid.UUID `json:"playlist_id,omitempty"`
	// SongID holds the value of the "song_id" field.
	SongID uuid.UUID `json:"song_id,omitempty"`
	// OrderIndex holds the value of the "order_index" field.
	OrderIndex int `json:"order_index,omitempty"`
	// AddedAt holds the value of the "added_at" field.
	AddedAt time.Time `json:"added_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlaylistSongQuery when eager-loading is set.
	Edges        PlaylistSongEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PlaylistSongEdges holds the relations/edges for other nodes in the graph.
type PlaylistSongEdges struct {
	// Playlist holds the value of the playlist edge.
	Playlist *Playlist `json:"playlist,omitempty"`
	// Song holds the value of the song edge.
	Song *Song `json:"song,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlaylistOrErr returns the Playlist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlaylistSongEdges) PlaylistOrErr() (*Playlist, error) {
	if e.Playlist != nil {
		return e.Playlist, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: playlist.Label}
	}
	return nil, &NotLoadedError{edge: "playlist"}
}

// SongOrErr returns the Song value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlaylistSongEdges) SongOrErr() (*Song, error) {
	if e.Song != nil {
		return e.Song, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: song.Label}
	}
	return nil, &NotLoadedError{edge: "song"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlaylistSong) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playlistsong.FieldOrderIndex:
			values[i] = new(sql.NullInt64)
		case playlistsong.FieldAddedAt:
			values[i] = new(sql.NullTime)
		case playlistsong.FieldID, playlistsong.FieldPlaylistID, playlistsong.FieldSongID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlaylistSong fields.
func (_m *PlaylistSong) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playlistsong.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case playlistsong.FieldPlaylistID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field playlist_id", values[i])
			} else if value != nil {
				_m.PlaylistID = *value
			}
		case playlistsong.FieldSongID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field song_id", values[i])
			} else if value != nil {
				_m.SongID = *value
			}
		case playlistsong.FieldOrderIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_index", values[i])
			} else if value.Valid {
				_m.OrderIndex = int(value.Int64)
			}
		case playlistsong.FieldAddedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field added_at", values[i])
			} else if value.Valid {
				_m.AddedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlaylistSong.
// This includes values selected through modifiers, order, etc.
func (_m *PlaylistSong) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlaylist queries the "playlist" edge of the PlaylistSong entity.
func (_m *PlaylistSong) QueryPlaylist() *PlaylistQuery {
	return NewPlaylistSongClient(_m.config).QueryPlaylist(_m)
}

// QuerySong queries the "song" edge of the PlaylistSong entity.
func (_m *PlaylistSong) QuerySong() *SongQuery {
	return NewPlaylistSongClient(_m.config).QuerySong(_m)
}

// Update returns a builder for updating this PlaylistSong.
// Note that you need to call PlaylistSong.Unwrap() before calling this method if this PlaylistSong
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlaylistSong) Update() *PlaylistSongUpdateOne {
	return NewPlaylistSongClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlaylistSong entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlaylistSong) Unwrap() *PlaylistSong {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlaylistSong is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlaylistSong) String() string {
	var builder strings.Builder
	builder.WriteString("PlaylistSong(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("playlist_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlaylistID))
	builder.WriteString(", ")
	builder.WriteString("song_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SongID))
	builder.WriteString(", ")
	builder.WriteString("order_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderIndex))
	builder.WriteString(", ")
	builder.WriteString("added_at=")
	builder.WriteString(_m.AddedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlaylistSongs is a parsable slice of PlaylistSong.
type PlaylistSongs []*PlaylistSong
