// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/playlist"
	"github.com/raymondchen/ly-backend/internal/ent/playlistsong"
	"github.com/raymondchen/ly-backend/internal/ent/predicate"
	"github.com/raymondchen/ly-backend/internal/ent/song"
)

// PlaylistSongQuery is the builder for querying PlaylistSong entities.
type PlaylistSongQuery struct {
	config
	ctx          *QueryContext
	order        []playlistsong.OrderOption
	inters       []Interceptor
	predicates   []predicate.PlaylistSong
	withPlaylist *PlaylistQuery
	withSong     *SongQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PlaylistSongQuery builder.
func (_q *PlaylistSongQuery) Where(ps ...predicate.PlaylistSong) *PlaylistSongQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PlaylistSongQuery) Limit(limit int) *PlaylistSongQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PlaylistSongQuery) Offset(offset int) *PlaylistSongQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PlaylistSongQuery) Unique(unique bool) *PlaylistSongQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PlaylistSongQuery) Order(o ...playlistsong.OrderOption) *PlaylistSongQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPlaylist chains the current query on the "playlist" edge.
func (_q *PlaylistSongQuery) QueryPlaylist() *PlaylistQuery {
	query := (&PlaylistClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(playlistsong.Table, playlistsong.FieldID, selector),
			sqlgraph.To(playlist.Table, playlist.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, playlistsong.PlaylistTable, playlistsong.PlaylistColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySong chains the current query on the "song" edge.
func (_q *PlaylistSongQuery) QuerySong() *SongQuery {
	query := (&SongClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(playlistsong.Table, playlistsong.FieldID, selector),
			sqlgraph.To(song.Table, song.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, playlistsong.SongTable, playlistsong.SongColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PlaylistSong entity from the query.
// Returns a *NotFoundError when no PlaylistSong was found.
func (_q *PlaylistSongQuery) First(ctx context.Context) (*PlaylistSong, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{playlistsong.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PlaylistSongQuery) FirstX(ctx context.Context) *PlaylistSong {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PlaylistSong ID from the query.
// Returns a *NotFoundError when no PlaylistSong ID was found.
func (_q *PlaylistSongQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{playlistsong.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PlaylistSongQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PlaylistSong entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PlaylistSong entity is found.
// Returns a *NotFoundError when no PlaylistSong entities are found.
func (_q *PlaylistSongQuery) Only(ctx context.Context) (*PlaylistSong, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{playlistsong.Label}
	default:
		return nil, &NotSingularError{playlistsong.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PlaylistSongQuery) OnlyX(ctx context.Context) *PlaylistSong {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PlaylistSong ID in the query.
// Returns a *NotSingularError when more than one PlaylistSong ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PlaylistSongQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{playlistsong.Label}
	default:
		err = &NotSingularError{playlistsong.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PlaylistSongQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PlaylistSongs.
func (_q *PlaylistSongQuery) All(ctx context.Context) ([]*PlaylistSong, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PlaylistSong, *PlaylistSongQuery]()
	return withInterceptors[[]*PlaylistSong](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PlaylistSongQuery) AllX(ctx context.Context) []*PlaylistSong {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PlaylistSong IDs.
func (_q *PlaylistSongQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(playlistsong.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PlaylistSongQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PlaylistSongQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PlaylistSongQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PlaylistSongQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PlaylistSongQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PlaylistSongQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PlaylistSongQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PlaylistSongQuery) Clone() *PlaylistSongQuery {
	if _q == nil {
		return nil
	}
	return &PlaylistSongQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]playlistsong.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.PlaylistSong{}, _q.predicates...),
		withPlaylist: _q.withPlaylist.Clone(),
		withSong:     _q.withSong.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPlaylist tells the query-builder to eager-load the nodes that are connected to
// the "playlist" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlaylistSongQuery) WithPlaylist(opts ...func(*PlaylistQuery)) *PlaylistSongQuery {
	query := (&PlaylistClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlaylist = query
	return _q
}

// WithSong tells the query-builder to eager-load the nodes that are connected to
// the "song" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlaylistSongQuery) WithSong(opts ...func(*SongQuery)) *PlaylistSongQuery {
	query := (&SongClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSong = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PlaylistID uuid.UUID `json:"playlist_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PlaylistSong.Query().
//		GroupBy(playlistsong.FieldPlaylistID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PlaylistSongQuery) GroupBy(field string, fields ...string) *PlaylistSongGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PlaylistSongGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = playlistsong.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PlaylistID uuid.UUID `json:"playlist_id,omitempty"`
//	}
//
//	client.PlaylistSong.Query().
//		Select(playlistsong.FieldPlaylistID).
//		Scan(ctx, &v)
func (_q *PlaylistSongQuery) Select(fields ...string) *PlaylistSongSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PlaylistSongSelect{PlaylistSongQuery: _q}
	sbuild.label = playlistsong.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PlaylistSongSelect configured with the given aggregations.
func (_q *PlaylistSongQuery) Aggregate(fns ...AggregateFunc) *PlaylistSongSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PlaylistSongQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !playlistsong.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PlaylistSongQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PlaylistSong, error) {
	var (
		nodes       = []*PlaylistSong{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPlaylist != nil,
			_q.withSong != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PlaylistSong).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PlaylistSong{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPlaylist; query != nil {
		if err := _q.loadPlaylist(ctx, query, nodes, nil,
			func(n *PlaylistSong, e *Playlist) { n.Edges.Playlist = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSong; query != nil {
		if err := _q.loadSong(ctx, query, nodes, nil,
			func(n *PlaylistSong, e *Song) { n.Edges.Song = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PlaylistSongQuery) loadPlaylist(ctx context.Context, query *PlaylistQuery, nodes []*PlaylistSong, init func(*PlaylistSong), assign func(*PlaylistSong, *Playlist)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PlaylistSong)
	for i := range nodes {
		fk := nodes[i].PlaylistID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(playlist.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "playlist_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PlaylistSongQuery) loadSong(ctx context.Context, query *SongQuery, nodes []*PlaylistSong, init func(*PlaylistSong), assign func(*PlaylistSong, *Song)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PlaylistSong)
	for i := range nodes {
		fk := nodes[i].SongID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(song.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "song_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PlaylistSongQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PlaylistSongQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(playlistsong.Table, playlistsong.Columns, sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playlistsong.FieldID)
		for i := range fields {
			if fields[i] != playlistsong.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPlaylist != nil {
			_spec.Node.AddColumnOnce(playlistsong.FieldPlaylistID)
		}
		if _q.withSong != nil {
			_spec.Node.AddColumnOnce(playlistsong.FieldSongID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PlaylistSongQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(playlistsong.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = playlistsong.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PlaylistSongGroupBy is the group-by builder for PlaylistSong entities.
type PlaylistSongGroupBy struct {
	selector
	build *PlaylistSongQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PlaylistSongGroupBy) Aggregate(fns ...AggregateFunc) *PlaylistSongGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PlaylistSongGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlaylistSongQuery, *PlaylistSongGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PlaylistSongGroupBy) sqlScan(ctx context.Context, root *PlaylistSongQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PlaylistSongSelect is the builder for selecting fields of PlaylistSong entities.
type PlaylistSongSelect struct {
	*PlaylistSongQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PlaylistSongSelect) Aggregate(fns ...AggregateFunc) *PlaylistSongSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PlaylistSongSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlaylistSongQuery, *PlaylistSongSelect](ctx, _s.PlaylistSongQuery, _s, _s.inters, v)
}

func (_s *PlaylistSongSelect) sqlScan(ctx context.Context, root *PlaylistSongQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
