// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/playlist"
	"github.com/raymondchen/ly-backend/internal/ent/playlistsong"
	"github.com/raymondchen/ly-backend/internal/ent/song"
)

// PlaylistSongCreate is the builder for creating a PlaylistSong entity.
type PlaylistSongCreate struct {
	config
	mutation *PlaylistSongMutation
	hooks    []Hook
}

// SetPlaylistID sets the "playlist_id" field.
func (_c *PlaylistSongCreate) SetPlaylistID(v uuid.UUID) *PlaylistSongCreate {
	_c.mutation.SetPlaylistID(v)
	return _c
}

// SetSongID sets the "song_id" field.
func (_c *PlaylistSongCreate) SetSongID(v uuid.UUID) *PlaylistSongCreate {
	_c.mutation.SetSongID(v)
	return _c
}

// SetOrderIndex sets the "order_index" field.
func (_c *PlaylistSongCreate) SetOrderIndex(v int) *PlaylistSongCreate {
	_c.mutation.SetOrderIndex(v)
	return _c
}

// SetAddedAt sets the "added_at" field.
func (_c *PlaylistSongCreate) SetAddedAt(v time.Time) *PlaylistSongCreate {
	_c.mutation.SetAddedAt(v)
	return _c
}

// SetNillableAddedAt sets the "added_at" field if the given value is not nil.
func (_c *PlaylistSongCreate) SetNillableAddedAt(v *time.Time) *PlaylistSongCreate {
	if v != nil {
		_c.SetAddedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlaylistSongCreate) SetID(v uuid.UUID) *PlaylistSongCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlaylistSongCreate) SetNillableID(v *uuid.UUID) *PlaylistSongCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPlaylist sets the "playlist" edge to the Playlist entity.
func (_c *PlaylistSongCreate) SetPlaylist(v *Playlist) *PlaylistSongCreate {
	return _c.SetPlaylistID(v.ID)
}

// SetSong sets the "song" edge to the Song entity.
func (_c *PlaylistSongCreate) SetSong(v *Song) *PlaylistSongCreate {
	return _c.SetSongID(v.ID)
}

// Mutation returns the PlaylistSongMutation object of the builder.
func (_c *PlaylistSongCreate) Mutation() *PlaylistSongMutation {
	return _c.mutation
}

// Save creates the PlaylistSong in the database.
func (_c *PlaylistSongCreate) Save(ctx context.Context) (*PlaylistSong, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlaylistSongCreate) SaveX(ctx context.Context) *PlaylistSong {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaylistSongCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaylistSongCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlaylistSongCreate) defaults() {
	if _, ok := _c.mutation.AddedAt(); !ok {
		v := playlistsong.DefaultAddedAt()
		_c.mutation.SetAddedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := playlistsong.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlaylistSongCreate) check() error {
	if _, ok := _c.mutation.PlaylistID(); !ok {
		return &ValidationError{Name: "playlist_id", err: errors.New(`ent: missing required field "PlaylistSong.playlist_id"`)}
	}
	if _, ok := _c.mutation.SongID(); !ok {
		return &ValidationError{Name: "song_id", err: errors.New(`ent: missing required field "PlaylistSong.song_id"`)}
	}
	if _, ok := _c.mutation.OrderIndex(); !ok {
		return &ValidationError{Name: "order_index", err: errors.New(`ent: missing required field "PlaylistSong.order_index"`)}
	}
	if _, ok := _c.mutation.AddedAt(); !ok {
		return &ValidationError{Name: "added_at", err: errors.New(`ent: missing required field "PlaylistSong.added_at"`)}
	}
	if len(_c.mutation.PlaylistIDs()) == 0 {
		return &ValidationError{Name: "playlist", err: errors.New(`ent: missing required edge "PlaylistSong.playlist"`)}
	}
	if len(_c.mutation.SongIDs()) == 0 {
		return &ValidationError{Name: "song", err: errors.New(`ent: missing required edge "PlaylistSong.song"`)}
	}
	return nil
}

func (_c *PlaylistSongCreate) sqlSave(ctx context.Context) (*PlaylistSong, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlaylistSongCreate) createSpec() (*PlaylistSong, *sqlgraph.CreateSpec) {
	var (
		_node = &PlaylistSong{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playlistsong.Table, sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OrderIndex(); ok {
		_spec.SetField(playlistsong.FieldOrderIndex, field.TypeInt, value)
		_node.OrderIndex = value
	}
	if value, ok := _c.mutation.AddedAt(); ok {
		_spec.SetField(playlistsong.FieldAddedAt, field.TypeTime, value)
		_node.AddedAt = value
	}
	if nodes := _c.mutation.PlaylistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.PlaylistTable,
			Columns: []string{playlistsong.PlaylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlaylistID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SongIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.SongTable,
			Columns: []string{playlistsong.SongColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SongID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlaylistSongCreateBulk is the builder for creating many PlaylistSong entities in bulk.
type PlaylistSongCreateBulk struct {
	config
	err      error
	builders []*PlaylistSongCreate
}

// Save creates the PlaylistSong entities in the database.
func (_c *PlaylistSongCreateBulk) Save(ctx context.Context) ([]*PlaylistSong, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlaylistSong, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlaylistSongMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlaylistSongCreateBulk) SaveX(ctx context.Context) []*PlaylistSong {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlaylistSongCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlaylistSongCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
