// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/playlist"
	"github.com/raymondchen/ly-backend/internal/ent/playlistsong"
	"github.com/raymondchen/ly-backend/internal/ent/predicate"
	"github.com/raymondchen/ly-backend/internal/ent/song"
)

// PlaylistSongUpdate is the builder for updating PlaylistSong entities.
type PlaylistSongUpdate struct {
	config
	hooks    []Hook
	mutation *PlaylistSongMutation
}

// Where appends a list predicates to the PlaylistSongUpdate builder.
func (_u *PlaylistSongUpdate) Where(ps ...predicate.PlaylistSong) *PlaylistSongUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlaylistID sets the "playlist_id" field.
func (_u *PlaylistSongUpdate) SetPlaylistID(v uuid.UUID) *PlaylistSongUpdate {
	_u.mutation.SetPlaylistID(v)
	return _u
}

// SetNillablePlaylistID sets the "playlist_id" field if the given value is not nil.
func (_u *PlaylistSongUpdate) SetNillablePlaylistID(v *uuid.UUID) *PlaylistSongUpdate {
	if v != nil {
		_u.SetPlaylistID(*v)
	}
	return _u
}

// SetSongID sets the "song_id" field.
func (_u *PlaylistSongUpdate) SetSongID(v uuid.UUID) *PlaylistSongUpdate {
	_u.mutation.SetSongID(v)
	return _u
}

// SetNillableSongID sets the "song_id" field if the given value is not nil.
func (_u *PlaylistSongUpdate) SetNillableSongID(v *uuid.UUID) *PlaylistSongUpdate {
	if v != nil {
		_u.SetSongID(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *PlaylistSongUpdate) SetOrderIndex(v int) *PlaylistSongUpdate {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *PlaylistSongUpdate) SetNillableOrderIndex(v *int) *PlaylistSongUpdate {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *PlaylistSongUpdate) AddOrderIndex(v int) *PlaylistSongUpdate {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetPlaylist sets the "playlist" edge to the Playlist entity.
func (_u *PlaylistSongUpdate) SetPlaylist(v *Playlist) *PlaylistSongUpdate {
	return _u.SetPlaylistID(v.ID)
}

// SetSong sets the "song" edge to the Song entity.
func (_u *PlaylistSongUpdate) SetSong(v *Song) *PlaylistSongUpdate {
	return _u.SetSongID(v.ID)
}

// Mutation returns the PlaylistSongMutation object of the builder.
func (_u *PlaylistSongUpdate) Mutation() *PlaylistSongMutation {
	return _u.mutation
}

// ClearPlaylist clears the "playlist" edge to the Playlist entity.
func (_u *PlaylistSongUpdate) ClearPlaylist() *PlaylistSongUpdate {
	_u.mutation.ClearPlaylist()
	return _u
}

// ClearSong clears the "song" edge to the Song entity.
func (_u *PlaylistSongUpdate) ClearSong() *PlaylistSongUpdate {
	_u.mutation.ClearSong()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlaylistSongUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaylistSongUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlaylistSongUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaylistSongUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlaylistSongUpdate) check() error {
	if _u.mutation.PlaylistCleared() && len(_u.mutation.PlaylistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlaylistSong.playlist"`)
	}
	if _u.mutation.SongCleared() && len(_u.mutation.SongIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlaylistSong.song"`)
	}
	return nil
}

func (_u *PlaylistSongUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playlistsong.Table, playlistsong.Columns, sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(playlistsong.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(playlistsong.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.PlaylistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.PlaylistTable,
			Columns: []string{playlistsong.PlaylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaylistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.PlaylistTable,
			Columns: []string{playlistsong.PlaylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SongCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.SongTable,
			Columns: []string{playlistsong.SongColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SongIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.SongTable,
			Columns: []string{playlistsong.SongColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playlistsong.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlaylistSongUpdateOne is the builder for updating a single PlaylistSong entity.
type PlaylistSongUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlaylistSongMutation
}

// SetPlaylistID sets the "playlist_id" field.
func (_u *PlaylistSongUpdateOne) SetPlaylistID(v uuid.UUID) *PlaylistSongUpdateOne {
	_u.mutation.SetPlaylistID(v)
	return _u
}

// SetNillablePlaylistID sets the "playlist_id" field if the given value is not nil.
func (_u *PlaylistSongUpdateOne) SetNillablePlaylistID(v *uuid.UUID) *PlaylistSongUpdateOne {
	if v != nil {
		_u.SetPlaylistID(*v)
	}
	return _u
}

// SetSongID sets the "song_id" field.
func (_u *PlaylistSongUpdateOne) SetSongID(v uuid.UUID) *PlaylistSongUpdateOne {
	_u.mutation.SetSongID(v)
	return _u
}

// SetNillableSongID sets the "song_id" field if the given value is not nil.
func (_u *PlaylistSongUpdateOne) SetNillableSongID(v *uuid.UUID) *PlaylistSongUpdateOne {
	if v != nil {
		_u.SetSongID(*v)
	}
	return _u
}

// SetOrderIndex sets the "order_index" field.
func (_u *PlaylistSongUpdateOne) SetOrderIndex(v int) *PlaylistSongUpdateOne {
	_u.mutation.ResetOrderIndex()
	_u.mutation.SetOrderIndex(v)
	return _u
}

// SetNillableOrderIndex sets the "order_index" field if the given value is not nil.
func (_u *PlaylistSongUpdateOne) SetNillableOrderIndex(v *int) *PlaylistSongUpdateOne {
	if v != nil {
		_u.SetOrderIndex(*v)
	}
	return _u
}

// AddOrderIndex adds value to the "order_index" field.
func (_u *PlaylistSongUpdateOne) AddOrderIndex(v int) *PlaylistSongUpdateOne {
	_u.mutation.AddOrderIndex(v)
	return _u
}

// SetPlaylist sets the "playlist" edge to the Playlist entity.
func (_u *PlaylistSongUpdateOne) SetPlaylist(v *Playlist) *PlaylistSongUpdateOne {
	return _u.SetPlaylistID(v.ID)
}

// SetSong sets the "song" edge to the Song entity.
func (_u *PlaylistSongUpdateOne) SetSong(v *Song) *PlaylistSongUpdateOne {
	return _u.SetSongID(v.ID)
}

// Mutation returns the PlaylistSongMutation object of the builder.
func (_u *PlaylistSongUpdateOne) Mutation() *PlaylistSongMutation {
	return _u.mutation
}

// ClearPlaylist clears the "playlist" edge to the Playlist entity.
func (_u *PlaylistSongUpdateOne) ClearPlaylist() *PlaylistSongUpdateOne {
	_u.mutation.ClearPlaylist()
	return _u
}

// ClearSong clears the "song" edge to the Song entity.
func (_u *PlaylistSongUpdateOne) ClearSong() *PlaylistSongUpdateOne {
	_u.mutation.ClearSong()
	return _u
}

// Where appends a list predicates to the PlaylistSongUpdate builder.
func (_u *PlaylistSongUpdateOne) Where(ps ...predicate.PlaylistSong) *PlaylistSongUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlaylistSongUpdateOne) Select(field string, fields ...string) *PlaylistSongUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlaylistSong entity.
func (_u *PlaylistSongUpdateOne) Save(ctx context.Context) (*PlaylistSong, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlaylistSongUpdateOne) SaveX(ctx context.Context) *PlaylistSong {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlaylistSongUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlaylistSongUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlaylistSongUpdateOne) check() error {
	if _u.mutation.PlaylistCleared() && len(_u.mutation.PlaylistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlaylistSong.playlist"`)
	}
	if _u.mutation.SongCleared() && len(_u.mutation.SongIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlaylistSong.song"`)
	}
	return nil
}

func (_u *PlaylistSongUpdateOne) sqlSave(ctx context.Context) (_node *PlaylistSong, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playlistsong.Table, playlistsong.Columns, sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlaylistSong.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playlistsong.FieldID)
		for _, f := range fields {
			if !playlistsong.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playlistsong.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderIndex(); ok {
		_spec.SetField(playlistsong.FieldOrderIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderIndex(); ok {
		_spec.AddField(playlistsong.FieldOrderIndex, field.TypeInt, value)
	}
	if _u.mutation.PlaylistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.PlaylistTable,
			Columns: []string{playlistsong.PlaylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaylistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.PlaylistTable,
			Columns: []string{playlistsong.PlaylistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SongCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.SongTable,
			Columns: []string{playlistsong.SongColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SongIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playlistsong.SongTable,
			Columns: []string{playlistsong.SongColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(song.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlaylistSong{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playlistsong.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
