// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/playlist"
	"github.com/raymondchen/ly-backend/internal/ent/playlistsong"
	"github.com/raymondchen/ly-backend/internal/ent/schema"
	"github.com/raymondchen/ly-backend/internal/ent/session"
	"github.com/raymondchen/ly-backend/internal/ent/settings"
	"github.com/raymondchen/ly-backend/internal/ent/song"
	"github.com/raymondchen/ly-backend/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	playlistFields := schema.Playlist{}.Fields()
	_ = playlistFields
	// playlistDescName is the schema descriptor for name field.
	playlistDescName := playlistFields[1].Descriptor()
	// playlist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	playlist.NameValidator = func() func(string) error {
		validators := playlistDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// playlistDescCreatedAt is the schema descriptor for created_at field.
	playlistDescCreatedAt := playlistFields[4].Descriptor()
	// playlist.DefaultCreatedAt holds the default value on creation for the created_at field.
	playlist.DefaultCreatedAt = playlistDescCreatedAt.Default.(func() time.Time)
	// playlistDescUpdatedAt is the schema descriptor for updated_at field.
	playlistDescUpdatedAt := playlistFields[5].Descriptor()
	// playlist.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	playlist.DefaultUpdatedAt = playlistDescUpdatedAt.Default.(func() time.Time)
	// playlist.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	playlist.UpdateDefaultUpdatedAt = playlistDescUpdatedAt.UpdateDefault.(func() time.Time)
	// playlistDescID is the schema descriptor for id field.
	playlistDescID := playlistFields[0].Descriptor()
	// playlist.DefaultID holds the default value on creation for the id field.
	playlist.DefaultID = playlistDescID.Default.(func() uuid.UUID)
	playlistsongFields := schema.PlaylistSong{}.Fields()
	_ = playlistsongFields
	// playlistsongDescAddedAt is the schema descriptor for added_at field.
	playlistsongDescAddedAt := playlistsongFields[4].Descriptor()
	// playlistsong.DefaultAddedAt holds the default value on creation for the added_at field.
	playlistsong.DefaultAddedAt = playlistsongDescAddedAt.Default.(func() time.Time)
	// playlistsongDescID is the schema descriptor for id field.
	playlistsongDescID := playlistsongFields[0].Descriptor()
	// playlistsong.DefaultID holds the default value on creation for the id field.
	playlistsong.DefaultID = playlistsongDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescToken is the schema descriptor for token field.
	sessionDescToken := sessionFields[2].Descriptor()
	// session.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	session.TokenValidator = func() func(string) error {
		validators := sessionDescToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token string) error {
			for _, fn := range fns {
				if err := fn(token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[4].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	settingsFields := schema.Settings{}.Fields()
	_ = settingsFields
	// settingsDescDisplayLines is the schema descriptor for display_lines field.
	settingsDescDisplayLines := settingsFields[2].Descriptor()
	// settings.DefaultDisplayLines holds the default value on creation for the display_lines field.
	settings.DefaultDisplayLines = settingsDescDisplayLines.Default.(int)
	// settingsDescFontSize is the schema descriptor for font_size field.
	settingsDescFontSize := settingsFields[3].Descriptor()
	// settings.DefaultFontSize holds the default value on creation for the font_size field.
	settings.DefaultFontSize = settingsDescFontSize.Default.(int)
	// settingsDescFontFamily is the schema descriptor for font_family field.
	settingsDescFontFamily := settingsFields[4].Descriptor()
	// settings.DefaultFontFamily holds the default value on creation for the font_family field.
	settings.DefaultFontFamily = settingsDescFontFamily.Default.(string)
	// settings.FontFamilyValidator is a validator for the "font_family" field. It is called by the builders before save.
	settings.FontFamilyValidator = settingsDescFontFamily.Validators[0].(func(string) error)
	// settingsDescTheme is the schema descriptor for theme field.
	settingsDescTheme := settingsFields[5].Descriptor()
	// settings.DefaultTheme holds the default value on creation for the theme field.
	settings.DefaultTheme = settingsDescTheme.Default.(string)
	// settings.ThemeValidator is a validator for the "theme" field. It is called by the builders before save.
	settings.ThemeValidator = settingsDescTheme.Validators[0].(func(string) error)
	// settingsDescShowBackground is the schema descriptor for show_background field.
	settingsDescShowBackground := settingsFields[6].Descriptor()
	// settings.DefaultShowBackground holds the default value on creation for the show_background field.
	settings.DefaultShowBackground = settingsDescShowBackground.Default.(bool)
	// settingsDescBackgroundColor is the schema descriptor for background_color field.
	settingsDescBackgroundColor := settingsFields[7].Descriptor()
	// settings.BackgroundColorValidator is a validator for the "background_color" field. It is called by the builders before save.
	settings.BackgroundColorValidator = settingsDescBackgroundColor.Validators[0].(func(string) error)
	// settingsDescTextColor is the schema descriptor for text_color field.
	settingsDescTextColor := settingsFields[8].Descriptor()
	// settings.TextColorValidator is a validator for the "text_color" field. It is called by the builders before save.
	settings.TextColorValidator = settingsDescTextColor.Validators[0].(func(string) error)
	// settingsDescHighlightColor is the schema descriptor for highlight_color field.
	settingsDescHighlightColor := settingsFields[9].Descriptor()
	// settings.HighlightColorValidator is a validator for the "highlight_color" field. It is called by the builders before save.
	settings.HighlightColorValidator = settingsDescHighlightColor.Validators[0].(func(string) error)
	// settingsDescAutoScroll is the schema descriptor for auto_scroll field.
	settingsDescAutoScroll := settingsFields[10].Descriptor()
	// settings.DefaultAutoScroll holds the default value on creation for the auto_scroll field.
	settings.DefaultAutoScroll = settingsDescAutoScroll.Default.(bool)
	// settingsDescScrollDuration is the schema descriptor for scroll_duration field.
	settingsDescScrollDuration := settingsFields[11].Descriptor()
	// settings.DefaultScrollDuration holds the default value on creation for the scroll_duration field.
	settings.DefaultScrollDuration = settingsDescScrollDuration.Default.(int)
	// settingsDescEnableAnimation is the schema descriptor for enable_animation field.
	settingsDescEnableAnimation := settingsFields[12].Descriptor()
	// settings.DefaultEnableAnimation holds the default value on creation for the enable_animation field.
	settings.DefaultEnableAnimation = settingsDescEnableAnimation.Default.(bool)
	// settingsDescCreatedAt is the schema descriptor for created_at field.
	settingsDescCreatedAt := settingsFields[13].Descriptor()
	// settings.DefaultCreatedAt holds the default value on creation for the created_at field.
	settings.DefaultCreatedAt = settingsDescCreatedAt.Default.(func() time.Time)
	// settingsDescUpdatedAt is the schema descriptor for updated_at field.
	settingsDescUpdatedAt := settingsFields[14].Descriptor()
	// settings.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	settings.DefaultUpdatedAt = settingsDescUpdatedAt.Default.(func() time.Time)
	// settings.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	settings.UpdateDefaultUpdatedAt = settingsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// settingsDescID is the schema descriptor for id field.
	settingsDescID := settingsFields[0].Descriptor()
	// settings.DefaultID holds the default value on creation for the id field.
	settings.DefaultID = settingsDescID.Default.(func() uuid.UUID)
	songFields := schema.Song{}.Fields()
	_ = songFields
	// songDescTitle is the schema descriptor for title field.
	songDescTitle := songFields[1].Descriptor()
	// song.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	song.TitleValidator = func() func(string) error {
		validators := songDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// songDescArtist is the schema descriptor for artist field.
	songDescArtist := songFields[2].Descriptor()
	// song.ArtistValidator is a validator for the "artist" field. It is called by the builders before save.
	song.ArtistValidator = songDescArtist.Validators[0].(func(string) error)
	// songDescLyrics is the schema descriptor for lyrics field.
	songDescLyrics := songFields[3].Descriptor()
	// song.LyricsValidator is a validator for the "lyrics" field. It is called by the builders before save.
	song.LyricsValidator = songDescLyrics.Validators[0].(func(string) error)
	// songDescLanguage is the schema descriptor for language field.
	songDescLanguage := songFields[6].Descriptor()
	// song.LanguageValidator is a validator for the "language" field. It is called by the builders before save.
	song.LanguageValidator = songDescLanguage.Validators[0].(func(string) error)
	// songDescCreatedAt is the schema descriptor for created_at field.
	songDescCreatedAt := songFields[8].Descriptor()
	// song.DefaultCreatedAt holds the default value on creation for the created_at field.
	song.DefaultCreatedAt = songDescCreatedAt.Default.(func() time.Time)
	// songDescUpdatedAt is the schema descriptor for updated_at field.
	songDescUpdatedAt := songFields[9].Descriptor()
	// song.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	song.DefaultUpdatedAt = songDescUpdatedAt.Default.(func() time.Time)
	// song.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	song.UpdateDefaultUpdatedAt = songDescUpdatedAt.UpdateDefault.(func() time.Time)
	// songDescID is the schema descriptor for id field.
	songDescID := songFields[0].Descriptor()
	// song.DefaultID holds the default value on creation for the id field.
	song.DefaultID = songDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[3].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[4].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
