// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/settings"
	"github.com/raymondchen/ly-backend/internal/ent/user"
)

// SettingsCreate is the builder for creating a Settings entity.
type SettingsCreate struct {
	config
	mutation *SettingsMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *SettingsCreate) SetUserID(v uuid.UUID) *SettingsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDisplayLines sets the "display_lines" field.
func (_c *SettingsCreate) SetDisplayLines(v int) *SettingsCreate {
	_c.mutation.SetDisplayLines(v)
	return _c
}

// SetNillableDisplayLines sets the "display_lines" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableDisplayLines(v *int) *SettingsCreate {
	if v != nil {
		_c.SetDisplayLines(*v)
	}
	return _c
}

// SetFontSize sets the "font_size" field.
func (_c *SettingsCreate) SetFontSize(v int) *SettingsCreate {
	_c.mutation.SetFontSize(v)
	return _c
}

// SetNillableFontSize sets the "font_size" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableFontSize(v *int) *SettingsCreate {
	if v != nil {
		_c.SetFontSize(*v)
	}
	return _c
}

// SetFontFamily sets the "font_family" field.
func (_c *SettingsCreate) SetFontFamily(v string) *SettingsCreate {
	_c.mutation.SetFontFamily(v)
	return _c
}

// SetNillableFontFamily sets the "font_family" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableFontFamily(v *string) *SettingsCreate {
	if v != nil {
		_c.SetFontFamily(*v)
	}
	return _c
}

// SetTheme sets the "theme" field.
func (_c *SettingsCreate) SetTheme(v string) *SettingsCreate {
	_c.mutation.SetTheme(v)
	return _c
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableTheme(v *string) *SettingsCreate {
	if v != nil {
		_c.SetTheme(*v)
	}
	return _c
}

// SetShowBackground sets the "show_background" field.
func (_c *SettingsCreate) SetShowBackground(v bool) *SettingsCreate {
	_c.mutation.SetShowBackground(v)
	return _c
}

// SetNillableShowBackground sets the "show_background" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableShowBackground(v *bool) *SettingsCreate {
	if v != nil {
		_c.SetShowBackground(*v)
	}
	return _c
}

// SetBackgroundColor sets the "background_color" field.
func (_c *SettingsCreate) SetBackgroundColor(v string) *SettingsCreate {
	_c.mutation.SetBackgroundColor(v)
	return _c
}

// SetNillableBackgroundColor sets the "background_color" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableBackgroundColor(v *string) *SettingsCreate {
	if v != nil {
		_c.SetBackgroundColor(*v)
	}
	return _c
}

// SetTextColor sets the "text_color" field.
func (_c *SettingsCreate) SetTextColor(v string) *SettingsCreate {
	_c.mutation.SetTextColor(v)
	return _c
}

// SetNillableTextColor sets the "text_color" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableTextColor(v *string) *SettingsCreate {
	if v != nil {
		_c.SetTextColor(*v)
	}
	return _c
}

// SetHighlightColor sets the "highlight_color" field.
func (_c *SettingsCreate) SetHighlightColor(v string) *SettingsCreate {
	_c.mutation.SetHighlightColor(v)
	return _c
}

// SetNillableHighlightColor sets the "highlight_color" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableHighlightColor(v *string) *SettingsCreate {
	if v != nil {
		_c.SetHighlightColor(*v)
	}
	return _c
}

// SetAutoScroll sets the "auto_scroll" field.
func (_c *SettingsCreate) SetAutoScroll(v bool) *SettingsCreate {
	_c.mutation.SetAutoScroll(v)
	return _c
}

// SetNillableAutoScroll sets the "auto_scroll" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableAutoScroll(v *bool) *SettingsCreate {
	if v != nil {
		_c.SetAutoScroll(*v)
	}
	return _c
}

// SetScrollDuration sets the "scroll_duration" field.
func (_c *SettingsCreate) SetScrollDuration(v int) *SettingsCreate {
	_c.mutation.SetScrollDuration(v)
	return _c
}

// SetNillableScrollDuration sets the "scroll_duration" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableScrollDuration(v *int) *SettingsCreate {
	if v != nil {
		_c.SetScrollDuration(*v)
	}
	return _c
}

// SetEnableAnimation sets the "enable_animation" field.
func (_c *SettingsCreate) SetEnableAnimation(v bool) *SettingsCreate {
	_c.mutation.SetEnableAnimation(v)
	return _c
}

// SetNillableEnableAnimation sets the "enable_animation" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableEnableAnimation(v *bool) *SettingsCreate {
	if v != nil {
		_c.SetEnableAnimation(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SettingsCreate) SetCreatedAt(v time.Time) *SettingsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableCreatedAt(v *time.Time) *SettingsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SettingsCreate) SetUpdatedAt(v time.Time) *SettingsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableUpdatedAt(v *time.Time) *SettingsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SettingsCreate) SetID(v uuid.UUID) *SettingsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableID(v *uuid.UUID) *SettingsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SettingsCreate) SetUser(v *User) *SettingsCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SettingsMutation object of the builder.
func (_c *SettingsCreate) Mutation() *SettingsMutation {
	return _c.mutation
}

// Save creates the Settings in the database.
func (_c *SettingsCreate) Save(ctx context.Context) (*Settings, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SettingsCreate) SaveX(ctx context.Context) *Settings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SettingsCreate) defaults() {
	if _, ok := _c.mutation.DisplayLines(); !ok {
		v := settings.DefaultDisplayLines
		_c.mutation.SetDisplayLines(v)
	}
	if _, ok := _c.mutation.FontSize(); !ok {
		v := settings.DefaultFontSize
		_c.mutation.SetFontSize(v)
	}
	if _, ok := _c.mutation.FontFamily(); !ok {
		v := settings.DefaultFontFamily
		_c.mutation.SetFontFamily(v)
	}
	if _, ok := _c.mutation.Theme(); !ok {
		v := settings.DefaultTheme
		_c.mutation.SetTheme(v)
	}
	if _, ok := _c.mutation.ShowBackground(); !ok {
		v := settings.DefaultShowBackground
		_c.mutation.SetShowBackground(v)
	}
	if _, ok := _c.mutation.AutoScroll(); !ok {
		v := settings.DefaultAutoScroll
		_c.mutation.SetAutoScroll(v)
	}
	if _, ok := _c.mutation.ScrollDuration(); !ok {
		v := settings.DefaultScrollDuration
		_c.mutation.SetScrollDuration(v)
	}
	if _, ok := _c.mutation.EnableAnimation(); !ok {
		v := settings.DefaultEnableAnimation
		_c.mutation.SetEnableAnimation(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := settings.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := settings.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := settings.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SettingsCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Settings.user_id"`)}
	}
	if _, ok := _c.mutation.DisplayLines(); !ok {
		return &ValidationError{Name: "display_lines", err: errors.New(`ent: missing required field "Settings.display_lines"`)}
	}
	if _, ok := _c.mutation.FontSize(); !ok {
		return &ValidationError{Name: "font_size", err: errors.New(`ent: missing required field "Settings.font_size"`)}
	}
	if _, ok := _c.mutation.FontFamily(); !ok {
		return &ValidationError{Name: "font_family", err: errors.New(`ent: missing required field "Settings.font_family"`)}
	}
	if v, ok := _c.mutation.FontFamily(); ok {
		if err := settings.FontFamilyValidator(v); err != nil {
			return &ValidationError{Name: "font_family", err: fmt.Errorf(`ent: validator failed for field "Settings.font_family": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Theme(); !ok {
		return &ValidationError{Name: "theme", err: errors.New(`ent: missing required field "Settings.theme"`)}
	}
	if v, ok := _c.mutation.Theme(); ok {
		if err := settings.ThemeValidator(v); err != nil {
			return &ValidationError{Name: "theme", err: fmt.Errorf(`ent: validator failed for field "Settings.theme": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ShowBackground(); !ok {
		return &ValidationError{Name: "show_background", err: errors.New(`ent: missing required field "Settings.show_background"`)}
	}
	if v, ok := _c.mutation.BackgroundColor(); ok {
		if err := settings.BackgroundColorValidator(v); err != nil {
			return &ValidationError{Name: "background_color", err: fmt.Errorf(`ent: validator failed for field "Settings.background_color": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TextColor(); ok {
		if err := settings.TextColorValidator(v); err != nil {
			return &ValidationError{Name: "text_color", err: fmt.Errorf(`ent: validator failed for field "Settings.text_color": %w`, err)}
		}
	}
	if v, ok := _c.mutation.HighlightColor(); ok {
		if err := settings.HighlightColorValidator(v); err != nil {
			return &ValidationError{Name: "highlight_color", err: fmt.Errorf(`ent: validator failed for field "Settings.highlight_color": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AutoScroll(); !ok {
		return &ValidationError{Name: "auto_scroll", err: errors.New(`ent: missing required field "Settings.auto_scroll"`)}
	}
	if _, ok := _c.mutation.ScrollDuration(); !ok {
		return &ValidationError{Name: "scroll_duration", err: errors.New(`ent: missing required field "Settings.scroll_duration"`)}
	}
	if _, ok := _c.mutation.EnableAnimation(); !ok {
		return &ValidationError{Name: "enable_animation", err: errors.New(`ent: missing required field "Settings.enable_animation"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Settings.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Settings.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Settings.user"`)}
	}
	return nil
}

func (_c *SettingsCreate) sqlSave(ctx context.Context) (*Settings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SettingsCreate) createSpec() (*Settings, *sqlgraph.CreateSpec) {
	var (
		_node = &Settings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(settings.Table, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DisplayLines(); ok {
		_spec.SetField(settings.FieldDisplayLines, field.TypeInt, value)
		_node.DisplayLines = value
	}
	if value, ok := _c.mutation.FontSize(); ok {
		_spec.SetField(settings.FieldFontSize, field.TypeInt, value)
		_node.FontSize = value
	}
	if value, ok := _c.mutation.FontFamily(); ok {
		_spec.SetField(settings.FieldFontFamily, field.TypeString, value)
		_node.FontFamily = value
	}
	if value, ok := _c.mutation.Theme(); ok {
		_spec.SetField(settings.FieldTheme, field.TypeString, value)
		_node.Theme = value
	}
	if value, ok := _c.mutation.ShowBackground(); ok {
		_spec.SetField(settings.FieldShowBackground, field.TypeBool, value)
		_node.ShowBackground = value
	}
	if value, ok := _c.mutation.BackgroundColor(); ok {
		_spec.SetField(settings.FieldBackgroundColor, field.TypeString, value)
		_node.BackgroundColor = &value
	}
	if value, ok := _c.mutation.TextColor(); ok {
		_spec.SetField(settings.FieldTextColor, field.TypeString, value)
		_node.TextColor = &value
	}
	if value, ok := _c.mutation.HighlightColor(); ok {
		_spec.SetField(settings.FieldHighlightColor, field.TypeString, value)
		_node.HighlightColor = &value
	}
	if value, ok := _c.mutation.AutoScroll(); ok {
		_spec.SetField(settings.FieldAutoScroll, field.TypeBool, value)
		_node.AutoScroll = value
	}
	if value, ok := _c.mutation.ScrollDuration(); ok {
		_spec.SetField(settings.FieldScrollDuration, field.TypeInt, value)
		_node.ScrollDuration = value
	}
	if value, ok := _c.mutation.EnableAnimation(); ok {
		_spec.SetField(settings.FieldEnableAnimation, field.TypeBool, value)
		_node.EnableAnimation = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(settings.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   settings.UserTable,
			Columns: []string{settings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SettingsCreateBulk is the builder for creating many Settings entities in bulk.
type SettingsCreateBulk struct {
	config
	err      error
	builders []*SettingsCreate
}

// Save creates the Settings entities in the database.
func (_c *SettingsCreateBulk) Save(ctx context.Context) ([]*Settings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Settings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SettingsCreateBulk) SaveX(ctx context.Context) []*Settings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
