// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/predicate"
	"github.com/raymondchen/ly-backend/internal/ent/settings"
	"github.com/raymondchen/ly-backend/internal/ent/user"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (_u *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SettingsUpdate) SetUserID(v uuid.UUID) *SettingsUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableUserID(v *uuid.UUID) *SettingsUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDisplayLines sets the "display_lines" field.
func (_u *SettingsUpdate) SetDisplayLines(v int) *SettingsUpdate {
	_u.mutation.ResetDisplayLines()
	_u.mutation.SetDisplayLines(v)
	return _u
}

// SetNillableDisplayLines sets the "display_lines" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableDisplayLines(v *int) *SettingsUpdate {
	if v != nil {
		_u.SetDisplayLines(*v)
	}
	return _u
}

// AddDisplayLines adds value to the "display_lines" field.
func (_u *SettingsUpdate) AddDisplayLines(v int) *SettingsUpdate {
	_u.mutation.AddDisplayLines(v)
	return _u
}

// SetFontSize sets the "font_size" field.
func (_u *SettingsUpdate) SetFontSize(v int) *SettingsUpdate {
	_u.mutation.ResetFontSize()
	_u.mutation.SetFontSize(v)
	return _u
}

// SetNillableFontSize sets the "font_size" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableFontSize(v *int) *SettingsUpdate {
	if v != nil {
		_u.SetFontSize(*v)
	}
	return _u
}

// AddFontSize adds value to the "font_size" field.
func (_u *SettingsUpdate) AddFontSize(v int) *SettingsUpdate {
	_u.mutation.AddFontSize(v)
	return _u
}

// SetFontFamily sets the "font_family" field.
func (_u *SettingsUpdate) SetFontFamily(v string) *SettingsUpdate {
	_u.mutation.SetFontFamily(v)
	return _u
}

// SetNillableFontFamily sets the "font_family" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableFontFamily(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetFontFamily(*v)
	}
	return _u
}

// SetTheme sets the "theme" field.
func (_u *SettingsUpdate) SetTheme(v string) *SettingsUpdate {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableTheme(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// SetShowBackground sets the "show_background" field.
func (_u *SettingsUpdate) SetShowBackground(v bool) *SettingsUpdate {
	_u.mutation.SetShowBackground(v)
	return _u
}

// SetNillableShowBackground sets the "show_background" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableShowBackground(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetShowBackground(*v)
	}
	return _u
}

// SetBackgroundColor sets the "background_color" field.
func (_u *SettingsUpdate) SetBackgroundColor(v string) *SettingsUpdate {
	_u.mutation.SetBackgroundColor(v)
	return _u
}

// SetNillableBackgroundColor sets the "background_color" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableBackgroundColor(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetBackgroundColor(*v)
	}
	return _u
}

// ClearBackgroundColor clears the value of the "background_color" field.
func (_u *SettingsUpdate) ClearBackgroundColor() *SettingsUpdate {
	_u.mutation.ClearBackgroundColor()
	return _u
}

// SetTextColor sets the "text_color" field.
func (_u *SettingsUpdate) SetTextColor(v string) *SettingsUpdate {
	_u.mutation.SetTextColor(v)
	return _u
}

// SetNillableTextColor sets the "text_color" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableTextColor(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetTextColor(*v)
	}
	return _u
}

// ClearTextColor clears the value of the "text_color" field.
func (_u *SettingsUpdate) ClearTextColor() *SettingsUpdate {
	_u.mutation.ClearTextColor()
	return _u
}

// SetHighlightColor sets the "highlight_color" field.
func (_u *SettingsUpdate) SetHighlightColor(v string) *SettingsUpdate {
	_u.mutation.SetHighlightColor(v)
	return _u
}

// SetNillableHighlightColor sets the "highlight_color" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableHighlightColor(v *string) *SettingsUpdate {
	if v != nil {
		_u.SetHighlightColor(*v)
	}
	return _u
}

// ClearHighlightColor clears the value of the "highlight_color" field.
func (_u *SettingsUpdate) ClearHighlightColor() *SettingsUpdate {
	_u.mutation.ClearHighlightColor()
	return _u
}

// SetAutoScroll sets the "auto_scroll" field.
func (_u *SettingsUpdate) SetAutoScroll(v bool) *SettingsUpdate {
	_u.mutation.SetAutoScroll(v)
	return _u
}

// SetNillableAutoScroll sets the "auto_scroll" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableAutoScroll(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetAutoScroll(*v)
	}
	return _u
}

// SetScrollDuration sets the "scroll_duration" field.
func (_u *SettingsUpdate) SetScrollDuration(v int) *SettingsUpdate {
	_u.mutation.ResetScrollDuration()
	_u.mutation.SetScrollDuration(v)
	return _u
}

// SetNillableScrollDuration sets the "scroll_duration" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableScrollDuration(v *int) *SettingsUpdate {
	if v != nil {
		_u.SetScrollDuration(*v)
	}
	return _u
}

// AddScrollDuration adds value to the "scroll_duration" field.
func (_u *SettingsUpdate) AddScrollDuration(v int) *SettingsUpdate {
	_u.mutation.AddScrollDuration(v)
	return _u
}

// SetEnableAnimation sets the "enable_animation" field.
func (_u *SettingsUpdate) SetEnableAnimation(v bool) *SettingsUpdate {
	_u.mutation.SetEnableAnimation(v)
	return _u
}

// SetNillableEnableAnimation sets the "enable_animation" field if the given value is not nil.
func (_u *SettingsUpdate) SetNillableEnableAnimation(v *bool) *SettingsUpdate {
	if v != nil {
		_u.SetEnableAnimation(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SettingsUpdate) SetUpdatedAt(v time.Time) *SettingsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SettingsUpdate) SetUser(v *User) *SettingsUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SettingsMutation object of the builder.
func (_u *SettingsUpdate) Mutation() *SettingsMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SettingsUpdate) ClearUser() *SettingsUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SettingsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SettingsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SettingsUpdate) check() error {
	if v, ok := _u.mutation.FontFamily(); ok {
		if err := settings.FontFamilyValidator(v); err != nil {
			return &ValidationError{Name: "font_family", err: fmt.Errorf(`ent: validator failed for field "Settings.font_family": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Theme(); ok {
		if err := settings.ThemeValidator(v); err != nil {
			return &ValidationError{Name: "theme", err: fmt.Errorf(`ent: validator failed for field "Settings.theme": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BackgroundColor(); ok {
		if err := settings.BackgroundColorValidator(v); err != nil {
			return &ValidationError{Name: "background_color", err: fmt.Errorf(`ent: validator failed for field "Settings.background_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TextColor(); ok {
		if err := settings.TextColorValidator(v); err != nil {
			return &ValidationError{Name: "text_color", err: fmt.Errorf(`ent: validator failed for field "Settings.text_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HighlightColor(); ok {
		if err := settings.HighlightColorValidator(v); err != nil {
			return &ValidationError{Name: "highlight_color", err: fmt.Errorf(`ent: validator failed for field "Settings.highlight_color": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Settings.user"`)
	}
	return nil
}

func (_u *SettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayLines(); ok {
		_spec.SetField(settings.FieldDisplayLines, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayLines(); ok {
		_spec.AddField(settings.FieldDisplayLines, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FontSize(); ok {
		_spec.SetField(settings.FieldFontSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFontSize(); ok {
		_spec.AddField(settings.FieldFontSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FontFamily(); ok {
		_spec.SetField(settings.FieldFontFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(settings.FieldTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShowBackground(); ok {
		_spec.SetField(settings.FieldShowBackground, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BackgroundColor(); ok {
		_spec.SetField(settings.FieldBackgroundColor, field.TypeString, value)
	}
	if _u.mutation.BackgroundColorCleared() {
		_spec.ClearField(settings.FieldBackgroundColor, field.TypeString)
	}
	if value, ok := _u.mutation.TextColor(); ok {
		_spec.SetField(settings.FieldTextColor, field.TypeString, value)
	}
	if _u.mutation.TextColorCleared() {
		_spec.ClearField(settings.FieldTextColor, field.TypeString)
	}
	if value, ok := _u.mutation.HighlightColor(); ok {
		_spec.SetField(settings.FieldHighlightColor, field.TypeString, value)
	}
	if _u.mutation.HighlightColorCleared() {
		_spec.ClearField(settings.FieldHighlightColor, field.TypeString)
	}
	if value, ok := _u.mutation.AutoScroll(); ok {
		_spec.SetField(settings.FieldAutoScroll, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ScrollDuration(); ok {
		_spec.SetField(settings.FieldScrollDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScrollDuration(); ok {
		_spec.AddField(settings.FieldScrollDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EnableAnimation(); ok {
		_spec.SetField(settings.FieldEnableAnimation, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   settings.UserTable,
			Columns: []string{settings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   settings.UserTable,
			Columns: []string{settings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetUserID sets the "user_id" field.
func (_u *SettingsUpdateOne) SetUserID(v uuid.UUID) *SettingsUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableUserID(v *uuid.UUID) *SettingsUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDisplayLines sets the "display_lines" field.
func (_u *SettingsUpdateOne) SetDisplayLines(v int) *SettingsUpdateOne {
	_u.mutation.ResetDisplayLines()
	_u.mutation.SetDisplayLines(v)
	return _u
}

// SetNillableDisplayLines sets the "display_lines" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableDisplayLines(v *int) *SettingsUpdateOne {
	if v != nil {
		_u.SetDisplayLines(*v)
	}
	return _u
}

// AddDisplayLines adds value to the "display_lines" field.
func (_u *SettingsUpdateOne) AddDisplayLines(v int) *SettingsUpdateOne {
	_u.mutation.AddDisplayLines(v)
	return _u
}

// SetFontSize sets the "font_size" field.
func (_u *SettingsUpdateOne) SetFontSize(v int) *SettingsUpdateOne {
	_u.mutation.ResetFontSize()
	_u.mutation.SetFontSize(v)
	return _u
}

// SetNillableFontSize sets the "font_size" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableFontSize(v *int) *SettingsUpdateOne {
	if v != nil {
		_u.SetFontSize(*v)
	}
	return _u
}

// AddFontSize adds value to the "font_size" field.
func (_u *SettingsUpdateOne) AddFontSize(v int) *SettingsUpdateOne {
	_u.mutation.AddFontSize(v)
	return _u
}

// SetFontFamily sets the "font_family" field.
func (_u *SettingsUpdateOne) SetFontFamily(v string) *SettingsUpdateOne {
	_u.mutation.SetFontFamily(v)
	return _u
}

// SetNillableFontFamily sets the "font_family" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableFontFamily(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetFontFamily(*v)
	}
	return _u
}

// SetTheme sets the "theme" field.
func (_u *SettingsUpdateOne) SetTheme(v string) *SettingsUpdateOne {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableTheme(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// SetShowBackground sets the "show_background" field.
func (_u *SettingsUpdateOne) SetShowBackground(v bool) *SettingsUpdateOne {
	_u.mutation.SetShowBackground(v)
	return _u
}

// SetNillableShowBackground sets the "show_background" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableShowBackground(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetShowBackground(*v)
	}
	return _u
}

// SetBackgroundColor sets the "background_color" field.
func (_u *SettingsUpdateOne) SetBackgroundColor(v string) *SettingsUpdateOne {
	_u.mutation.SetBackgroundColor(v)
	return _u
}

// SetNillableBackgroundColor sets the "background_color" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableBackgroundColor(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetBackgroundColor(*v)
	}
	return _u
}

// ClearBackgroundColor clears the value of the "background_color" field.
func (_u *SettingsUpdateOne) ClearBackgroundColor() *SettingsUpdateOne {
	_u.mutation.ClearBackgroundColor()
	return _u
}

// SetTextColor sets the "text_color" field.
func (_u *SettingsUpdateOne) SetTextColor(v string) *SettingsUpdateOne {
	_u.mutation.SetTextColor(v)
	return _u
}

// SetNillableTextColor sets the "text_color" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableTextColor(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetTextColor(*v)
	}
	return _u
}

// ClearTextColor clears the value of the "text_color" field.
func (_u *SettingsUpdateOne) ClearTextColor() *SettingsUpdateOne {
	_u.mutation.ClearTextColor()
	return _u
}

// SetHighlightColor sets the "highlight_color" field.
func (_u *SettingsUpdateOne) SetHighlightColor(v string) *SettingsUpdateOne {
	_u.mutation.SetHighlightColor(v)
	return _u
}

// SetNillableHighlightColor sets the "highlight_color" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableHighlightColor(v *string) *SettingsUpdateOne {
	if v != nil {
		_u.SetHighlightColor(*v)
	}
	return _u
}

// ClearHighlightColor clears the value of the "highlight_color" field.
func (_u *SettingsUpdateOne) ClearHighlightColor() *SettingsUpdateOne {
	_u.mutation.ClearHighlightColor()
	return _u
}

// SetAutoScroll sets the "auto_scroll" field.
func (_u *SettingsUpdateOne) SetAutoScroll(v bool) *SettingsUpdateOne {
	_u.mutation.SetAutoScroll(v)
	return _u
}

// SetNillableAutoScroll sets the "auto_scroll" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableAutoScroll(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetAutoScroll(*v)
	}
	return _u
}

// SetScrollDuration sets the "scroll_duration" field.
func (_u *SettingsUpdateOne) SetScrollDuration(v int) *SettingsUpdateOne {
	_u.mutation.ResetScrollDuration()
	_u.mutation.SetScrollDuration(v)
	return _u
}

// SetNillableScrollDuration sets the "scroll_duration" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableScrollDuration(v *int) *SettingsUpdateOne {
	if v != nil {
		_u.SetScrollDuration(*v)
	}
	return _u
}

// AddScrollDuration adds value to the "scroll_duration" field.
func (_u *SettingsUpdateOne) AddScrollDuration(v int) *SettingsUpdateOne {
	_u.mutation.AddScrollDuration(v)
	return _u
}

// SetEnableAnimation sets the "enable_animation" field.
func (_u *SettingsUpdateOne) SetEnableAnimation(v bool) *SettingsUpdateOne {
	_u.mutation.SetEnableAnimation(v)
	return _u
}

// SetNillableEnableAnimation sets the "enable_animation" field if the given value is not nil.
func (_u *SettingsUpdateOne) SetNillableEnableAnimation(v *bool) *SettingsUpdateOne {
	if v != nil {
		_u.SetEnableAnimation(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SettingsUpdateOne) SetUpdatedAt(v time.Time) *SettingsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SettingsUpdateOne) SetUser(v *User) *SettingsUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SettingsMutation object of the builder.
func (_u *SettingsUpdateOne) Mutation() *SettingsMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SettingsUpdateOne) ClearUser() *SettingsUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the SettingsUpdate builder.
func (_u *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Settings entity.
func (_u *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SettingsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SettingsUpdateOne) check() error {
	if v, ok := _u.mutation.FontFamily(); ok {
		if err := settings.FontFamilyValidator(v); err != nil {
			return &ValidationError{Name: "font_family", err: fmt.Errorf(`ent: validator failed for field "Settings.font_family": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Theme(); ok {
		if err := settings.ThemeValidator(v); err != nil {
			return &ValidationError{Name: "theme", err: fmt.Errorf(`ent: validator failed for field "Settings.theme": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BackgroundColor(); ok {
		if err := settings.BackgroundColorValidator(v); err != nil {
			return &ValidationError{Name: "background_color", err: fmt.Errorf(`ent: validator failed for field "Settings.background_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TextColor(); ok {
		if err := settings.TextColorValidator(v); err != nil {
			return &ValidationError{Name: "text_color", err: fmt.Errorf(`ent: validator failed for field "Settings.text_color": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HighlightColor(); ok {
		if err := settings.HighlightColorValidator(v); err != nil {
			return &ValidationError{Name: "highlight_color", err: fmt.Errorf(`ent: validator failed for field "Settings.highlight_color": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Settings.user"`)
	}
	return nil
}

func (_u *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayLines(); ok {
		_spec.SetField(settings.FieldDisplayLines, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayLines(); ok {
		_spec.AddField(settings.FieldDisplayLines, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FontSize(); ok {
		_spec.SetField(settings.FieldFontSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFontSize(); ok {
		_spec.AddField(settings.FieldFontSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FontFamily(); ok {
		_spec.SetField(settings.FieldFontFamily, field.TypeString, value)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(settings.FieldTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShowBackground(); ok {
		_spec.SetField(settings.FieldShowBackground, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BackgroundColor(); ok {
		_spec.SetField(settings.FieldBackgroundColor, field.TypeString, value)
	}
	if _u.mutation.BackgroundColorCleared() {
		_spec.ClearField(settings.FieldBackgroundColor, field.TypeString)
	}
	if value, ok := _u.mutation.TextColor(); ok {
		_spec.SetField(settings.FieldTextColor, field.TypeString, value)
	}
	if _u.mutation.TextColorCleared() {
		_spec.ClearField(settings.FieldTextColor, field.TypeString)
	}
	if value, ok := _u.mutation.HighlightColor(); ok {
		_spec.SetField(settings.FieldHighlightColor, field.TypeString, value)
	}
	if _u.mutation.HighlightColorCleared() {
		_spec.ClearField(settings.FieldHighlightColor, field.TypeString)
	}
	if value, ok := _u.mutation.AutoScroll(); ok {
		_spec.SetField(settings.FieldAutoScroll, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ScrollDuration(); ok {
		_spec.SetField(settings.FieldScrollDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScrollDuration(); ok {
		_spec.AddField(settings.FieldScrollDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EnableAnimation(); ok {
		_spec.SetField(settings.FieldEnableAnimation, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   settings.UserTable,
			Columns: []string{settings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   settings.UserTable,
			Columns: []string{settings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Settings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
