// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/settings"
	"github.com/raymondchen/ly-backend/internal/ent/user"
)

// Settings is the model entity for the Settings schema.
type Settings struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// DisplayLines holds the value of the "display_lines" field.
	DisplayLines int `json:"display_lines,omitempty"`
	// FontSize holds the value of the "font_size" field.
	FontSize int `json:"font_size,omitempty"`
	// FontFamily holds the value of the "font_family" field.
	FontFamily string `json:"font_family,omitempty"`
	// Theme holds the value of the "theme" field.
	Theme string `json:"theme,omitempty"`
	// ShowBackground holds the value of the "show_background" field.
	ShowBackground bool `json:"show_background,omitempty"`
	// BackgroundColor holds the value of the "background_color" field.
	BackgroundColor *string `json:"background_color,omitempty"`
	// TextColor holds the value of the "text_color" field.
	TextColor *string `json:"text_color,omitempty"`
	// HighlightColor holds the value of the "highlight_color" field.
	HighlightColor *string `json:"highlight_color,omitempty"`
	// AutoScroll holds the value of the "auto_scroll" field.
	AutoScroll bool `json:"auto_scroll,omitempty"`
	// ScrollDuration holds the value of the "scroll_duration" field.
	ScrollDuration int `json:"scroll_duration,omitempty"`
	// EnableAnimation holds the value of the "enable_animation" field.
	EnableAnimation bool `json:"enable_animation,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SettingsQuery when eager-loading is set.
	Edges        SettingsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SettingsEdges holds the relations/edges for other nodes in the graph.
type SettingsEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SettingsEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Settings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case settings.FieldShowBackground, settings.FieldAutoScroll, settings.FieldEnableAnimation:
			values[i] = new(sql.NullBool)
		case settings.FieldDisplayLines, settings.FieldFontSize, settings.FieldScrollDuration:
			values[i] = new(sql.NullInt64)
		case settings.FieldFontFamily, settings.FieldTheme, settings.FieldBackgroundColor, settings.FieldTextColor, settings.FieldHighlightColor:
			values[i] = new(sql.NullString)
		case settings.FieldCreatedAt, settings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case settings.FieldID, settings.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Settings fields.
func (_m *Settings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case settings.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case settings.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case settings.FieldDisplayLines:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_lines", values[i])
			} else if value.Valid {
				_m.DisplayLines = int(value.Int64)
			}
		case settings.FieldFontSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field font_size", values[i])
			} else if value.Valid {
				_m.FontSize = int(value.Int64)
			}
		case settings.FieldFontFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field font_family", values[i])
			} else if value.Valid {
				_m.FontFamily = value.String
			}
		case settings.FieldTheme:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field theme", values[i])
			} else if value.Valid {
				_m.Theme = value.String
			}
		case settings.FieldShowBackground:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field show_background", values[i])
			} else if value.Valid {
				_m.ShowBackground = value.Bool
			}
		case settings.FieldBackgroundColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field background_color", values[i])
			} else if value.Valid {
				_m.BackgroundColor = new(string)
				*_m.BackgroundColor = value.String
			}
		case settings.FieldTextColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text_color", values[i])
			} else if value.Valid {
				_m.TextColor = new(string)
				*_m.TextColor = value.String
			}
		case settings.FieldHighlightColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field highlight_color", values[i])
			} else if value.Valid {
				_m.HighlightColor = new(string)
				*_m.HighlightColor = value.String
			}
		case settings.FieldAutoScroll:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_scroll", values[i])
			} else if value.Valid {
				_m.AutoScroll = value.Bool
			}
		case settings.FieldScrollDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field scroll_duration", values[i])
			} else if value.Valid {
				_m.ScrollDuration = int(value.Int64)
			}
		case settings.FieldEnableAnimation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable_animation", values[i])
			} else if value.Valid {
				_m.EnableAnimation = value.Bool
			}
		case settings.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case settings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Settings.
// This includes values selected through modifiers, order, etc.
func (_m *Settings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Settings entity.
func (_m *Settings) QueryUser() *UserQuery {
	return NewSettingsClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Settings.
// Note that you need to call Settings.Unwrap() before calling this method if this Settings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Settings) Update() *SettingsUpdateOne {
	return NewSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Settings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Settings) Unwrap() *Settings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Settings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Settings) String() string {
	var builder strings.Builder
	builder.WriteString("Settings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("display_lines=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayLines))
	builder.WriteString(", ")
	builder.WriteString("font_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FontSize))
	builder.WriteString(", ")
	builder.WriteString("font_family=")
	builder.WriteString(_m.FontFamily)
	builder.WriteString(", ")
	builder.WriteString("theme=")
	builder.WriteString(_m.Theme)
	builder.WriteString(", ")
	builder.WriteString("show_background=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShowBackground))
	builder.WriteString(", ")
	if v := _m.BackgroundColor; v != nil {
		builder.WriteString("background_color=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TextColor; v != nil {
		builder.WriteString("text_color=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.HighlightColor; v != nil {
		builder.WriteString("highlight_color=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("auto_scroll=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoScroll))
	builder.WriteString(", ")
	builder.WriteString("scroll_duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScrollDuration))
	builder.WriteString(", ")
	builder.WriteString("enable_animation=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnableAnimation))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SettingsSlice is a parsable slice of Settings.
type SettingsSlice []*Settings
