// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/playlistsong"
	"github.com/raymondchen/ly-backend/internal/ent/predicate"
	"github.com/raymondchen/ly-backend/internal/ent/song"
	"github.com/raymondchen/ly-backend/internal/ent/user"
)

// SongUpdate is the builder for updating Song entities.
type SongUpdate struct {
	config
	hooks    []Hook
	mutation *SongMutation
}

// Where appends a list predicates to the SongUpdate builder.
func (_u *SongUpdate) Where(ps ...predicate.Song) *SongUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *SongUpdate) SetTitle(v string) *SongUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SongUpdate) SetNillableTitle(v *string) *SongUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetArtist sets the "artist" field.
func (_u *SongUpdate) SetArtist(v string) *SongUpdate {
	_u.mutation.SetArtist(v)
	return _u
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_u *SongUpdate) SetNillableArtist(v *string) *SongUpdate {
	if v != nil {
		_u.SetArtist(*v)
	}
	return _u
}

// ClearArtist clears the value of the "artist" field.
func (_u *SongUpdate) ClearArtist() *SongUpdate {
	_u.mutation.ClearArtist()
	return _u
}

// SetLyrics sets the "lyrics" field.
func (_u *SongUpdate) SetLyrics(v string) *SongUpdate {
	_u.mutation.SetLyrics(v)
	return _u
}

// SetNillableLyrics sets the "lyrics" field if the given value is not nil.
func (_u *SongUpdate) SetNillableLyrics(v *string) *SongUpdate {
	if v != nil {
		_u.SetLyrics(*v)
	}
	return _u
}

// SetLrcTimestamps sets the "lrc_timestamps" field.
func (_u *SongUpdate) SetLrcTimestamps(v string) *SongUpdate {
	_u.mutation.SetLrcTimestamps(v)
	return _u
}

// SetNillableLrcTimestamps sets the "lrc_timestamps" field if the given value is not nil.
func (_u *SongUpdate) SetNillableLrcTimestamps(v *string) *SongUpdate {
	if v != nil {
		_u.SetLrcTimestamps(*v)
	}
	return _u
}

// ClearLrcTimestamps clears the value of the "lrc_timestamps" field.
func (_u *SongUpdate) ClearLrcTimestamps() *SongUpdate {
	_u.mutation.ClearLrcTimestamps()
	return _u
}

// SetLrcContent sets the "lrc_content" field.
func (_u *SongUpdate) SetLrcContent(v map[string]interface{}) *SongUpdate {
	_u.mutation.SetLrcContent(v)
	return _u
}

// ClearLrcContent clears the value of the "lrc_content" field.
func (_u *SongUpdate) ClearLrcContent() *SongUpdate {
	_u.mutation.ClearLrcContent()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *SongUpdate) SetLanguage(v string) *SongUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *SongUpdate) SetNillableLanguage(v *string) *SongUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *SongUpdate) ClearLanguage() *SongUpdate {
	_u.mutation.ClearLanguage()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SongUpdate) SetUserID(v uuid.UUID) *SongUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SongUpdate) SetNillableUserID(v *uuid.UUID) *SongUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SongUpdate) SetUpdatedAt(v time.Time) *SongUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SongUpdate) SetUser(v *User) *SongUpdate {
	return _u.SetUserID(v.ID)
}

// AddPlaylistSongIDs adds the "playlist_songs" edge to the PlaylistSong entity by IDs.
func (_u *SongUpdate) AddPlaylistSongIDs(ids ...uuid.UUID) *SongUpdate {
	_u.mutation.AddPlaylistSongIDs(ids...)
	return _u
}

// AddPlaylistSongs adds the "playlist_songs" edges to the PlaylistSong entity.
func (_u *SongUpdate) AddPlaylistSongs(v ...*PlaylistSong) *SongUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaylistSongIDs(ids...)
}

// Mutation returns the SongMutation object of the builder.
func (_u *SongUpdate) Mutation() *SongMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SongUpdate) ClearUser() *SongUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlaylistSongs clears all "playlist_songs" edges to the PlaylistSong entity.
func (_u *SongUpdate) ClearPlaylistSongs() *SongUpdate {
	_u.mutation.ClearPlaylistSongs()
	return _u
}

// RemovePlaylistSongIDs removes the "playlist_songs" edge to PlaylistSong entities by IDs.
func (_u *SongUpdate) RemovePlaylistSongIDs(ids ...uuid.UUID) *SongUpdate {
	_u.mutation.RemovePlaylistSongIDs(ids...)
	return _u
}

// RemovePlaylistSongs removes "playlist_songs" edges to PlaylistSong entities.
func (_u *SongUpdate) RemovePlaylistSongs(v ...*PlaylistSong) *SongUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaylistSongIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SongUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SongUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SongUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SongUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SongUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := song.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SongUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := song.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Song.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Artist(); ok {
		if err := song.ArtistValidator(v); err != nil {
			return &ValidationError{Name: "artist", err: fmt.Errorf(`ent: validator failed for field "Song.artist": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lyrics(); ok {
		if err := song.LyricsValidator(v); err != nil {
			return &ValidationError{Name: "lyrics", err: fmt.Errorf(`ent: validator failed for field "Song.lyrics": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := song.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Song.language": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Song.user"`)
	}
	return nil
}

func (_u *SongUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(song.Table, song.Columns, sqlgraph.NewFieldSpec(song.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(song.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Artist(); ok {
		_spec.SetField(song.FieldArtist, field.TypeString, value)
	}
	if _u.mutation.ArtistCleared() {
		_spec.ClearField(song.FieldArtist, field.TypeString)
	}
	if value, ok := _u.mutation.Lyrics(); ok {
		_spec.SetField(song.FieldLyrics, field.TypeString, value)
	}
	if value, ok := _u.mutation.LrcTimestamps(); ok {
		_spec.SetField(song.FieldLrcTimestamps, field.TypeString, value)
	}
	if _u.mutation.LrcTimestampsCleared() {
		_spec.ClearField(song.FieldLrcTimestamps, field.TypeString)
	}
	if value, ok := _u.mutation.LrcContent(); ok {
		_spec.SetField(song.FieldLrcContent, field.TypeJSON, value)
	}
	if _u.mutation.LrcContentCleared() {
		_spec.ClearField(song.FieldLrcContent, field.TypeJSON)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(song.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(song.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(song.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   song.UserTable,
			Columns: []string{song.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   song.UserTable,
			Columns: []string{song.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaylistSongsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   song.PlaylistSongsTable,
			Columns: []string{song.PlaylistSongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaylistSongsIDs(); len(nodes) > 0 && !_u.mutation.PlaylistSongsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   song.PlaylistSongsTable,
			Columns: []string{song.PlaylistSongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaylistSongsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   song.PlaylistSongsTable,
			Columns: []string{song.PlaylistSongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{song.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SongUpdateOne is the builder for updating a single Song entity.
type SongUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SongMutation
}

// SetTitle sets the "title" field.
func (_u *SongUpdateOne) SetTitle(v string) *SongUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableTitle(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetArtist sets the "artist" field.
func (_u *SongUpdateOne) SetArtist(v string) *SongUpdateOne {
	_u.mutation.SetArtist(v)
	return _u
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableArtist(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetArtist(*v)
	}
	return _u
}

// ClearArtist clears the value of the "artist" field.
func (_u *SongUpdateOne) ClearArtist() *SongUpdateOne {
	_u.mutation.ClearArtist()
	return _u
}

// SetLyrics sets the "lyrics" field.
func (_u *SongUpdateOne) SetLyrics(v string) *SongUpdateOne {
	_u.mutation.SetLyrics(v)
	return _u
}

// SetNillableLyrics sets the "lyrics" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableLyrics(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetLyrics(*v)
	}
	return _u
}

// SetLrcTimestamps sets the "lrc_timestamps" field.
func (_u *SongUpdateOne) SetLrcTimestamps(v string) *SongUpdateOne {
	_u.mutation.SetLrcTimestamps(v)
	return _u
}

// SetNillableLrcTimestamps sets the "lrc_timestamps" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableLrcTimestamps(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetLrcTimestamps(*v)
	}
	return _u
}

// ClearLrcTimestamps clears the value of the "lrc_timestamps" field.
func (_u *SongUpdateOne) ClearLrcTimestamps() *SongUpdateOne {
	_u.mutation.ClearLrcTimestamps()
	return _u
}

// SetLrcContent sets the "lrc_content" field.
func (_u *SongUpdateOne) SetLrcContent(v map[string]interface{}) *SongUpdateOne {
	_u.mutation.SetLrcContent(v)
	return _u
}

// ClearLrcContent clears the value of the "lrc_content" field.
func (_u *SongUpdateOne) ClearLrcContent() *SongUpdateOne {
	_u.mutation.ClearLrcContent()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *SongUpdateOne) SetLanguage(v string) *SongUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableLanguage(v *string) *SongUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *SongUpdateOne) ClearLanguage() *SongUpdateOne {
	_u.mutation.ClearLanguage()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SongUpdateOne) SetUserID(v uuid.UUID) *SongUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SongUpdateOne) SetNillableUserID(v *uuid.UUID) *SongUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SongUpdateOne) SetUpdatedAt(v time.Time) *SongUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SongUpdateOne) SetUser(v *User) *SongUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddPlaylistSongIDs adds the "playlist_songs" edge to the PlaylistSong entity by IDs.
func (_u *SongUpdateOne) AddPlaylistSongIDs(ids ...uuid.UUID) *SongUpdateOne {
	_u.mutation.AddPlaylistSongIDs(ids...)
	return _u
}

// AddPlaylistSongs adds the "playlist_songs" edges to the PlaylistSong entity.
func (_u *SongUpdateOne) AddPlaylistSongs(v ...*PlaylistSong) *SongUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaylistSongIDs(ids...)
}

// Mutation returns the SongMutation object of the builder.
func (_u *SongUpdateOne) Mutation() *SongMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SongUpdateOne) ClearUser() *SongUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlaylistSongs clears all "playlist_songs" edges to the PlaylistSong entity.
func (_u *SongUpdateOne) ClearPlaylistSongs() *SongUpdateOne {
	_u.mutation.ClearPlaylistSongs()
	return _u
}

// RemovePlaylistSongIDs removes the "playlist_songs" edge to PlaylistSong entities by IDs.
func (_u *SongUpdateOne) RemovePlaylistSongIDs(ids ...uuid.UUID) *SongUpdateOne {
	_u.mutation.RemovePlaylistSongIDs(ids...)
	return _u
}

// RemovePlaylistSongs removes "playlist_songs" edges to PlaylistSong entities.
func (_u *SongUpdateOne) RemovePlaylistSongs(v ...*PlaylistSong) *SongUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaylistSongIDs(ids...)
}

// Where appends a list predicates to the SongUpdate builder.
func (_u *SongUpdateOne) Where(ps ...predicate.Song) *SongUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SongUpdateOne) Select(field string, fields ...string) *SongUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Song entity.
func (_u *SongUpdateOne) Save(ctx context.Context) (*Song, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SongUpdateOne) SaveX(ctx context.Context) *Song {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SongUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SongUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SongUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := song.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SongUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := song.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Song.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Artist(); ok {
		if err := song.ArtistValidator(v); err != nil {
			return &ValidationError{Name: "artist", err: fmt.Errorf(`ent: validator failed for field "Song.artist": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lyrics(); ok {
		if err := song.LyricsValidator(v); err != nil {
			return &ValidationError{Name: "lyrics", err: fmt.Errorf(`ent: validator failed for field "Song.lyrics": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := song.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Song.language": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Song.user"`)
	}
	return nil
}

func (_u *SongUpdateOne) sqlSave(ctx context.Context) (_node *Song, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(song.Table, song.Columns, sqlgraph.NewFieldSpec(song.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Song.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, song.FieldID)
		for _, f := range fields {
			if !song.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != song.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(song.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Artist(); ok {
		_spec.SetField(song.FieldArtist, field.TypeString, value)
	}
	if _u.mutation.ArtistCleared() {
		_spec.ClearField(song.FieldArtist, field.TypeString)
	}
	if value, ok := _u.mutation.Lyrics(); ok {
		_spec.SetField(song.FieldLyrics, field.TypeString, value)
	}
	if value, ok := _u.mutation.LrcTimestamps(); ok {
		_spec.SetField(song.FieldLrcTimestamps, field.TypeString, value)
	}
	if _u.mutation.LrcTimestampsCleared() {
		_spec.ClearField(song.FieldLrcTimestamps, field.TypeString)
	}
	if value, ok := _u.mutation.LrcContent(); ok {
		_spec.SetField(song.FieldLrcContent, field.TypeJSON, value)
	}
	if _u.mutation.LrcContentCleared() {
		_spec.ClearField(song.FieldLrcContent, field.TypeJSON)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(song.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(song.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(song.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   song.UserTable,
			Columns: []string{song.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   song.UserTable,
			Columns: []string{song.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaylistSongsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   song.PlaylistSongsTable,
			Columns: []string{song.PlaylistSongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaylistSongsIDs(); len(nodes) > 0 && !_u.mutation.PlaylistSongsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   song.PlaylistSongsTable,
			Columns: []string{song.PlaylistSongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaylistSongsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   song.PlaylistSongsTable,
			Columns: []string{song.PlaylistSongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Song{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{song.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
