// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/song"
	"github.com/raymondchen/ly-backend/internal/ent/user"
)

// Song is the model entity for the Song schema.
type Song struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Artist holds the value of the "artist" field.
	Artist *string `json:"artist,omitempty"`
	// Lyrics holds the value of the "lyrics" field.
	Lyrics string `json:"lyrics,omitempty"`
	// LrcTimestamps holds the value of the "lrc_timestamps" field.
	LrcTimestamps *string `json:"lrc_timestamps,omitempty"`
	// LrcContent holds the value of the "lrc_content" field.
	LrcContent map[string]interface{} `json:"lrc_content,omitempty"`
	// Language holds the value of the "language" field.
	Language *string `json:"language,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SongQuery when eager-loading is set.
	Edges        SongEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SongEdges holds the relations/edges for other nodes in the graph.
type SongEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// PlaylistSongs holds the value of the playlist_songs edge.
	PlaylistSongs []*PlaylistSong `json:"playlist_songs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SongEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PlaylistSongsOrErr returns the PlaylistSongs value or an error if the edge
// was not loaded in eager-loading.
func (e SongEdges) PlaylistSongsOrErr() ([]*PlaylistSong, error) {
	if e.loadedTypes[1] {
		return e.PlaylistSongs, nil
	}
	return nil, &NotLoadedError{edge: "playlist_songs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Song) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case song.FieldLrcContent:
			values[i] = new([]byte)
		case song.FieldTitle, song.FieldArtist, song.FieldLyrics, song.FieldLrcTimestamps, song.FieldLanguage:
			values[i] = new(sql.NullString)
		case song.FieldCreatedAt, song.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case song.FieldID, song.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Song fields.
func (_m *Song) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case song.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case song.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case song.FieldArtist:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field artist", values[i])
			} else if value.Valid {
				_m.Artist = new(string)
				*_m.Artist = value.String
			}
		case song.FieldLyrics:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lyrics", values[i])
			} else if value.Valid {
				_m.Lyrics = value.String
			}
		case song.FieldLrcTimestamps:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lrc_timestamps", values[i])
			} else if value.Valid {
				_m.LrcTimestamps = new(string)
				*_m.LrcTimestamps = value.String
			}
		case song.FieldLrcContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field lrc_content", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LrcContent); err != nil {
					return fmt.Errorf("unmarshal field lrc_content: %w", err)
				}
			}
		case song.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = new(string)
				*_m.Language = value.String
			}
		case song.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case song.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case song.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Song.
// This includes values selected through modifiers, order, etc.
func (_m *Song) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Song entity.
func (_m *Song) QueryUser() *UserQuery {
	return NewSongClient(_m.config).QueryUser(_m)
}

// QueryPlaylistSongs queries the "playlist_songs" edge of the Song entity.
func (_m *Song) QueryPlaylistSongs() *PlaylistSongQuery {
	return NewSongClient(_m.config).QueryPlaylistSongs(_m)
}

// Update returns a builder for updating this Song.
// Note that you need to call Song.Unwrap() before calling this method if this Song
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Song) Update() *SongUpdateOne {
	return NewSongClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Song entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Song) Unwrap() *Song {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Song is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Song) String() string {
	var builder strings.Builder
	builder.WriteString("Song(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Artist; v != nil {
		builder.WriteString("artist=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("lyrics=")
	builder.WriteString(_m.Lyrics)
	builder.WriteString(", ")
	if v := _m.LrcTimestamps; v != nil {
		builder.WriteString("lrc_timestamps=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("lrc_content=")
	builder.WriteString(fmt.Sprintf("%v", _m.LrcContent))
	builder.WriteString(", ")
	if v := _m.Language; v != nil {
		builder.WriteString("language=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Songs is a parsable slice of Song.
type Songs []*Song
