// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/raymondchen/ly-backend/internal/ent/playlistsong"
	"github.com/raymondchen/ly-backend/internal/ent/song"
	"github.com/raymondchen/ly-backend/internal/ent/user"
)

// SongCreate is the builder for creating a Song entity.
type SongCreate struct {
	config
	mutation *SongMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *SongCreate) SetTitle(v string) *SongCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetArtist sets the "artist" field.
func (_c *SongCreate) SetArtist(v string) *SongCreate {
	_c.mutation.SetArtist(v)
	return _c
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_c *SongCreate) SetNillableArtist(v *string) *SongCreate {
	if v != nil {
		_c.SetArtist(*v)
	}
	return _c
}

// SetLyrics sets the "lyrics" field.
func (_c *SongCreate) SetLyrics(v string) *SongCreate {
	_c.mutation.SetLyrics(v)
	return _c
}

// SetLrcTimestamps sets the "lrc_timestamps" field.
func (_c *SongCreate) SetLrcTimestamps(v string) *SongCreate {
	_c.mutation.SetLrcTimestamps(v)
	return _c
}

// SetNillableLrcTimestamps sets the "lrc_timestamps" field if the given value is not nil.
func (_c *SongCreate) SetNillableLrcTimestamps(v *string) *SongCreate {
	if v != nil {
		_c.SetLrcTimestamps(*v)
	}
	return _c
}

// SetLrcContent sets the "lrc_content" field.
func (_c *SongCreate) SetLrcContent(v map[string]interface{}) *SongCreate {
	_c.mutation.SetLrcContent(v)
	return _c
}

// SetLanguage sets the "language" field.
func (_c *SongCreate) SetLanguage(v string) *SongCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *SongCreate) SetNillableLanguage(v *string) *SongCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SongCreate) SetUserID(v uuid.UUID) *SongCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SongCreate) SetCreatedAt(v time.Time) *SongCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SongCreate) SetNillableCreatedAt(v *time.Time) *SongCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SongCreate) SetUpdatedAt(v time.Time) *SongCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SongCreate) SetNillableUpdatedAt(v *time.Time) *SongCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SongCreate) SetID(v uuid.UUID) *SongCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SongCreate) SetNillableID(v *uuid.UUID) *SongCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SongCreate) SetUser(v *User) *SongCreate {
	return _c.SetUserID(v.ID)
}

// AddPlaylistSongIDs adds the "playlist_songs" edge to the PlaylistSong entity by IDs.
func (_c *SongCreate) AddPlaylistSongIDs(ids ...uuid.UUID) *SongCreate {
	_c.mutation.AddPlaylistSongIDs(ids...)
	return _c
}

// AddPlaylistSongs adds the "playlist_songs" edges to the PlaylistSong entity.
func (_c *SongCreate) AddPlaylistSongs(v ...*PlaylistSong) *SongCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPlaylistSongIDs(ids...)
}

// Mutation returns the SongMutation object of the builder.
func (_c *SongCreate) Mutation() *SongMutation {
	return _c.mutation
}

// Save creates the Song in the database.
func (_c *SongCreate) Save(ctx context.Context) (*Song, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SongCreate) SaveX(ctx context.Context) *Song {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SongCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SongCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SongCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := song.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := song.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := song.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SongCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Song.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := song.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Song.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Artist(); ok {
		if err := song.ArtistValidator(v); err != nil {
			return &ValidationError{Name: "artist", err: fmt.Errorf(`ent: validator failed for field "Song.artist": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Lyrics(); !ok {
		return &ValidationError{Name: "lyrics", err: errors.New(`ent: missing required field "Song.lyrics"`)}
	}
	if v, ok := _c.mutation.Lyrics(); ok {
		if err := song.LyricsValidator(v); err != nil {
			return &ValidationError{Name: "lyrics", err: fmt.Errorf(`ent: validator failed for field "Song.lyrics": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Language(); ok {
		if err := song.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Song.language": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Song.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Song.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Song.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Song.user"`)}
	}
	return nil
}

func (_c *SongCreate) sqlSave(ctx context.Context) (*Song, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SongCreate) createSpec() (*Song, *sqlgraph.CreateSpec) {
	var (
		_node = &Song{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(song.Table, sqlgraph.NewFieldSpec(song.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(song.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Artist(); ok {
		_spec.SetField(song.FieldArtist, field.TypeString, value)
		_node.Artist = &value
	}
	if value, ok := _c.mutation.Lyrics(); ok {
		_spec.SetField(song.FieldLyrics, field.TypeString, value)
		_node.Lyrics = value
	}
	if value, ok := _c.mutation.LrcTimestamps(); ok {
		_spec.SetField(song.FieldLrcTimestamps, field.TypeString, value)
		_node.LrcTimestamps = &value
	}
	if value, ok := _c.mutation.LrcContent(); ok {
		_spec.SetField(song.FieldLrcContent, field.TypeJSON, value)
		_node.LrcContent = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(song.FieldLanguage, field.TypeString, value)
		_node.Language = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(song.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(song.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   song.UserTable,
			Columns: []string{song.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlaylistSongsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   song.PlaylistSongsTable,
			Columns: []string{song.PlaylistSongsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlistsong.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SongCreateBulk is the builder for creating many Song entities in bulk.
type SongCreateBulk struct {
	config
	err      error
	builders []*SongCreate
}

// Save creates the Song entities in the database.
func (_c *SongCreateBulk) Save(ctx context.Context) ([]*Song, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Song, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SongMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SongCreateBulk) SaveX(ctx context.Context) []*Song {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SongCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SongCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
