// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Playlist is the predicate function for playlist builders.
type Playlist func(*sql.Selector)

// PlaylistSong is the predicate function for playlistsong builders.
type PlaylistSong func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// Song is the predicate function for song builders.
type Song func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
